//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by StorageClassGenerator
//
//     Do not change code in this file, it will get lost when the file gets 
//     auto generated again. Write your code into DictionaryChild.cs.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;
using System.Threading;
using StorageLib;


namespace DataModelSamples  {


  public partial class DictionaryChild: IStorageItemGeneric<DictionaryChild> {

    #region Properties
    //      ----------

    /// <summary>
    /// Unique identifier for DictionaryChild. Gets set once DictionaryChild gets added to DC.Data.
    /// </summary>
    public int Key { get; private set; }
    internal static void SetKey(IStorageItem dictionaryChild, int key, bool _) {
      ((DictionaryChild)dictionaryChild).Key = key;
    }


    /// <summary>
    /// Stores only dates but no times.
    ///  </summary>
    public DateTime Date { get; private set; }


    public DictionaryParent Parent { get; private set; }


    /// <summary>
    /// Headers written to first line in CSV file
    /// </summary>
    internal static readonly string[] Headers = {"Key", "Date", "Parent"};


    /// <summary>
    /// None existing DictionaryChild
    /// </summary>
    internal static DictionaryChild NoDictionaryChild = new DictionaryChild(DateTime.MinValue.Date, DictionaryParent.NoDictionaryParent, isStoring: false);
    #endregion


    #region Events
    //      ------

    /// <summary>
    /// Content of DictionaryChild has changed. Gets only raised for changes occurring after loading DC.Data with previously stored data.
    /// </summary>
    public event Action</*old*/DictionaryChild, /*new*/DictionaryChild>? HasChanged;
    #endregion


    #region Constructors
    //      ------------

    /// <summary>
    /// DictionaryChild Constructor. If isStoring is true, adds DictionaryChild to DC.Data.DictionaryChilds.
    /// </summary>
    public DictionaryChild(DateTime date, DictionaryParent parent, bool isStoring = true) {
      Key = StorageExtensions.NoKey;
      Date = date.Floor(Rounding.Days);
      Parent = parent;
      Parent.AddToChildren(this);
      onConstruct();
      if (DC.Data.IsTransaction) {
        DC.Data.AddTransaction(new TransactionItem(2,TransactionActivityEnum.New, Key, this));
      }

      if (isStoring) {
        Store();
      }
    }
    partial void onConstruct();


    /// <summary>
    /// Cloning constructor. It will copy all data from original except any collection (children).
    /// </summary>
    #pragma warning disable CS8618 // Children collections are uninitialized.
    public DictionaryChild(DictionaryChild original) {
    #pragma warning restore CS8618 //
      Key = StorageExtensions.NoKey;
      Date = original.Date;
      Parent = original.Parent;
      onCloned(this);
    }
    partial void onCloned(DictionaryChild clone);


    /// <summary>
    /// Constructor for DictionaryChild read from CSV file
    /// </summary>
    private DictionaryChild(int key, CsvReader csvReader){
      Key = key;
      Date = csvReader.ReadDate();
      var dictionaryParentKey = csvReader.ReadInt();
      Parent = DC.Data._DictionaryParents.GetItem(dictionaryParentKey)??
        throw new Exception($"Read DictionaryChild from CSV file: Cannot find Parent with key {dictionaryParentKey}." + Environment.NewLine + 
          csvReader.PresentContent);
      if (Parent!=DictionaryParent.NoDictionaryParent) {
        Parent.AddToChildren(this);
      }
      onCsvConstruct();
    }
    partial void onCsvConstruct();


    /// <summary>
    /// New DictionaryChild read from CSV file
    /// </summary>
    internal static DictionaryChild Create(int key, CsvReader csvReader) {
      return new DictionaryChild(key, csvReader);
    }


    /// <summary>
    /// Verify that dictionaryChild.Parent exists.
    /// </summary>
    internal static bool Verify(DictionaryChild dictionaryChild) {
      if (dictionaryChild.Parent==DictionaryParent.NoDictionaryParent) return false;
      return true;
    }
    #endregion


    #region Methods
    //      -------

    /// <summary>
    /// Adds DictionaryChild to DC.Data.DictionaryChilds.<br/>
    /// Throws an Exception when DictionaryChild is already stored.
    /// </summary>
    public void Store() {
      if (Key>=0) {
        throw new Exception($"DictionaryChild cannot be stored again in DC.Data, key {Key} is greater equal 0." + Environment.NewLine + ToString());
      }

      var isCancelled = false;
      onStoring(ref isCancelled);
      if (isCancelled) return;

      if (Parent.Key<0) {
        throw new Exception($"Cannot store child DictionaryChild '{this}'.Parent to DictionaryParent '{Parent}' because parent is not stored yet.");
      }
      DC.Data._DictionaryChilds.Add(this);
      onStored();
    }
    partial void onStoring(ref bool isCancelled);
    partial void onStored();


    /// <summary>
    /// Estimated number of UTF8 characters needed to write DictionaryChild to CSV file
    /// </summary>
    public const int EstimatedLineLength = 16;


    /// <summary>
    /// Write DictionaryChild to CSV file
    /// </summary>
    internal static void Write(DictionaryChild dictionaryChild, CsvWriter csvWriter) {
      dictionaryChild.onCsvWrite();
      csvWriter.WriteDate(dictionaryChild.Date);
      if (dictionaryChild.Parent.Key<0) throw new Exception($"Cannot write dictionaryChild '{dictionaryChild}' to CSV File, because Parent is not stored in DC.Data.DictionaryParents.");

      csvWriter.Write(dictionaryChild.Parent.Key.ToString());
    }
    partial void onCsvWrite();


    /// <summary>
    /// Updates DictionaryChild with the provided values
    /// </summary>
    public void Update(DateTime date, DictionaryParent parent) {
      if (Key>=0){
        if (parent.Key<0) {
          throw new Exception($"DictionaryChild.Update(): It is illegal to add stored DictionaryChild '{this}'" + Environment.NewLine + 
            $"to Parent '{parent}', which is not stored.");
        }
      }
      var clone = new DictionaryChild(this);
      var isCancelled = false;
      onUpdating(date, parent, ref isCancelled);
      if (isCancelled) return;


      //remove not yet updated item from parents which will be removed by update
      var hasParentChanged = Parent!=parent || Date!=date;
      if (hasParentChanged) {
        Parent.RemoveFromChildren(this);
      }

      //update properties and detect if any value has changed
      var isChangeDetected = false;
      var dateRounded = date.Floor(Rounding.Days);
      if (Date!=dateRounded) {
        Date = dateRounded;
        isChangeDetected = true;
      }
      if (Parent!=parent) {
        Parent = parent;
        isChangeDetected = true;
      }

      //add updated item to parents which have been newly added during update
      if (hasParentChanged) {
        Parent.AddToChildren(this);
      }
      if (isChangeDetected) {
        onUpdated(clone);
        if (Key>=0) {
          DC.Data._DictionaryChilds.ItemHasChanged(clone, this);
        } else if (DC.Data.IsTransaction) {
          DC.Data.AddTransaction(new TransactionItem(2, TransactionActivityEnum.Update, Key, this, oldItem: clone));
        }
        HasChanged?.Invoke(clone, this);
      }
    }
    partial void onUpdating(DateTime date, DictionaryParent parent, ref bool isCancelled);
    partial void onUpdated(DictionaryChild old);


    /// <summary>
    /// Updates this DictionaryChild with values from CSV file
    /// </summary>
    internal static void Update(DictionaryChild dictionaryChild, CsvReader csvReader){
      dictionaryChild.Date = csvReader.ReadDate();
        var parent = DC.Data._DictionaryParents.GetItem(csvReader.ReadInt())??
          DictionaryParent.NoDictionaryParent;
      if (dictionaryChild.Parent!=parent) {
        if (dictionaryChild.Parent!=DictionaryParent.NoDictionaryParent) {
          dictionaryChild.Parent.RemoveFromChildren(dictionaryChild);
        }
        dictionaryChild.Parent = parent;
        dictionaryChild.Parent.AddToChildren(dictionaryChild);
      }
      dictionaryChild.onCsvUpdate();
    }
    partial void onCsvUpdate();


    /// <summary>
    /// Removes DictionaryChild from DC.Data.DictionaryChilds.
    /// </summary>
    public void Release() {
      if (Key<0) {
        throw new Exception($"DictionaryChild.Release(): DictionaryChild '{this}' is not stored in DC.Data, key is {Key}.");
      }
      onReleased();
      DC.Data._DictionaryChilds.Remove(Key);
    }
    partial void onReleased();


    /// <summary>
    /// Removes DictionaryChild from parents as part of a transaction rollback of the new() statement.
    /// </summary>
    internal static void RollbackItemNew(IStorageItem item) {
      var dictionaryChild = (DictionaryChild) item;
      if (dictionaryChild.Parent!=DictionaryParent.NoDictionaryParent) {
        dictionaryChild.Parent.RemoveFromChildren(dictionaryChild);
      }
      dictionaryChild.onRollbackItemNew();
    }
    partial void onRollbackItemNew();


    /// <summary>
    /// Releases DictionaryChild from DC.Data.DictionaryChilds as part of a transaction rollback of Store().
    /// </summary>
    internal static void RollbackItemStore(IStorageItem item) {
      var dictionaryChild = (DictionaryChild) item;
      dictionaryChild.onRollbackItemStored();
    }
    partial void onRollbackItemStored();


    /// <summary>
    /// Restores the DictionaryChild item data as it was before the last update as part of a transaction rollback.
    /// </summary>
    internal static void RollbackItemUpdate(IStorageItem oldStorageItem, IStorageItem newStorageItem) {
      var oldItem = (DictionaryChild) oldStorageItem;//an item clone with the values before item was updated
      var item = (DictionaryChild) newStorageItem;//is the instance whose values should be restored

      // remove updated item from parents
      var hasParentChanged = oldItem.Parent!=item.Parent || oldItem.Date!=item.Date;
      if (hasParentChanged) {
        item.Parent.RemoveFromChildren(item);
      }

      // updated item: restore old values
      item.Date = oldItem.Date;
      item.Parent = oldItem.Parent;

      // add item with previous values to parents
      if (hasParentChanged) {
        item.Parent.AddToChildren(item);
      }
      item.onRollbackItemUpdated(oldItem);
    }
    partial void onRollbackItemUpdated(DictionaryChild oldDictionaryChild);


    /// <summary>
    /// Adds DictionaryChild to DC.Data.DictionaryChilds as part of a transaction rollback of Release().
    /// </summary>
    internal static void RollbackItemRelease(IStorageItem item) {
      var dictionaryChild = (DictionaryChild) item;
      dictionaryChild.onRollbackItemRelease();
    }
    partial void onRollbackItemRelease();


    /// <summary>
    /// Returns property values for tracing. Parents are shown with their key instead their content.
    /// </summary>
    public string ToTraceString() {
      var returnString =
        $"{this.GetKeyOrHash()}|" +
        $" {Date.ToShortDateString()}|" +
        $" Parent {Parent.GetKeyOrHash()}";
      onToTraceString(ref returnString);
      return returnString;
    }
    partial void onToTraceString(ref string returnString);


    /// <summary>
    /// Returns property values
    /// </summary>
    public string ToShortString() {
      var returnString =
        $"{Key.ToKeyString()}," +
        $" {Date.ToShortDateString()}," +
        $" {Parent.ToShortString()}";
      onToShortString(ref returnString);
      return returnString;
    }
    partial void onToShortString(ref string returnString);


    /// <summary>
    /// Returns all property names and values
    /// </summary>
    public override string ToString() {
      var returnString =
        $"Key: {Key.ToKeyString()}," +
        $" Date: {Date.ToShortDateString()}," +
        $" Parent: {Parent.ToShortString()};";
      onToString(ref returnString);
      return returnString;
    }
    partial void onToString(ref string returnString);
    #endregion
  }
}
