//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by StorageClassGenerator
//
//     Do not change code in this file, it will get lost when the file gets 
//     auto generated again. Write your code into DictionaryWithPropertyNameChild.cs.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;
using System.Threading;
using StorageLib;


namespace DataModelSamples  {


  public partial class DictionaryWithPropertyNameChild: IStorageItem<DictionaryWithPropertyNameChild> {

    #region Properties
    //      ----------

    /// <summary>
    /// Unique identifier for DictionaryWithPropertyNameChild. Gets set once DictionaryWithPropertyNameChild gets added to DC.Data.
    /// </summary>
    public int Key { get; private set; }
    internal static void SetKey(IStorageItem dictionaryWithPropertyNameChild, int key, bool _) {
      ((DictionaryWithPropertyNameChild)dictionaryWithPropertyNameChild).Key = key;
    }


    /// <summary>
    /// Stores only dates but no times.
    ///  </summary>
    public DateTime Date1 { get; private set; }


    /// <summary>
    /// Stores only dates but no times.
    ///  </summary>
    public DateTime Date2 { get; private set; }


    public DictionaryWithPropertyNameParent Parent { get; private set; }


    /// <summary>
    /// Headers written to first line in CSV file
    /// </summary>
    internal static readonly string[] Headers = {"Key", "Date1", "Date2", "Parent"};


    /// <summary>
    /// None existing DictionaryWithPropertyNameChild, used as a temporary place holder when reading a CSV file
    /// which was not compacted. It might create first a later deleted item linking to a 
    /// deleted parent. In this case, the parent property gets set to NoDictionaryWithPropertyNameChild. Once the CSV
    /// file is completely read, that child will actually be deleted (released) and Verify()
    /// ensures that there are no stored children with links to NoDictionaryWithPropertyNameChild.
    /// </summary>
    internal static DictionaryWithPropertyNameChild NoDictionaryWithPropertyNameChild = new DictionaryWithPropertyNameChild(DateTime.MinValue.Date, DateTime.MinValue.Date, DictionaryWithPropertyNameParent.NoDictionaryWithPropertyNameParent, isStoring: false);
    #endregion


    #region Events
    //      ------

    /// <summary>
    /// Content of DictionaryWithPropertyNameChild has changed. Gets only raised for changes occurring after loading DC.Data with previously stored data.
    /// </summary>
    public event Action</*old*/DictionaryWithPropertyNameChild, /*new*/DictionaryWithPropertyNameChild>? HasChanged;
    #endregion


    #region Constructors
    //      ------------

    /// <summary>
    /// DictionaryWithPropertyNameChild Constructor. If isStoring is true, adds DictionaryWithPropertyNameChild to DC.Data.DictionaryWithPropertyNameChilds.
    /// </summary>
    public DictionaryWithPropertyNameChild(DateTime date1, DateTime date2, DictionaryWithPropertyNameParent parent, bool isStoring = true) {
      Key = StorageExtensions.NoKey;
      Date1 = date1.Floor(Rounding.Days);
      Date2 = date2.Floor(Rounding.Days);
      Parent = parent;
      Parent.AddToChildren(this);
      onConstruct();
      if (DC.Data.IsTransaction) {
        DC.Data.AddTransaction(new TransactionItem(30,TransactionActivityEnum.New, Key, this));
      }

      if (isStoring) {
        Store();
      }
    }
    partial void onConstruct();


    /// <summary>
    /// Cloning constructor. It will copy all data from original except any collection (children).
    /// </summary>
    #pragma warning disable CS8618 // Children collections are uninitialized.
    public DictionaryWithPropertyNameChild(DictionaryWithPropertyNameChild original) {
    #pragma warning restore CS8618 //
      Key = StorageExtensions.NoKey;
      Date1 = original.Date1;
      Date2 = original.Date2;
      Parent = original.Parent;
      onCloned(this);
    }
    partial void onCloned(DictionaryWithPropertyNameChild clone);


    /// <summary>
    /// Constructor for DictionaryWithPropertyNameChild read from CSV file
    /// </summary>
    private DictionaryWithPropertyNameChild(int key, CsvReader csvReader){
      Key = key;
      Date1 = csvReader.ReadDate();
      Date2 = csvReader.ReadDate();
      var dictionaryWithPropertyNameParentKey = csvReader.ReadInt();
      Parent = DC.Data._DictionaryWithPropertyNameParents.GetItem(dictionaryWithPropertyNameParentKey)?? DictionaryWithPropertyNameParent.NoDictionaryWithPropertyNameParent;
      if (Parent!=DictionaryWithPropertyNameParent.NoDictionaryWithPropertyNameParent) {
        Parent.AddToChildren(this);
      }
      onCsvConstruct();
    }
    partial void onCsvConstruct();


    /// <summary>
    /// New DictionaryWithPropertyNameChild read from CSV file
    /// </summary>
    internal static DictionaryWithPropertyNameChild Create(int key, CsvReader csvReader) {
      return new DictionaryWithPropertyNameChild(key, csvReader);
    }


    /// <summary>
    /// Verify that dictionaryWithPropertyNameChild.Parent exists.
    /// </summary>
    internal static bool Verify(DictionaryWithPropertyNameChild dictionaryWithPropertyNameChild) {
      if (dictionaryWithPropertyNameChild.Parent==DictionaryWithPropertyNameParent.NoDictionaryWithPropertyNameParent) return false;
      return true;
    }
    #endregion


    #region Methods
    //      -------

    /// <summary>
    /// Adds DictionaryWithPropertyNameChild to DC.Data.DictionaryWithPropertyNameChilds.<br/>
    /// Throws an Exception when DictionaryWithPropertyNameChild is already stored.
    /// </summary>
    public void Store() {
      if (Key>=0) {
        throw new Exception($"DictionaryWithPropertyNameChild cannot be stored again in DC.Data, key {Key} is greater equal 0." + Environment.NewLine + ToString());
      }

      var isCancelled = false;
      onStoring(ref isCancelled);
      if (isCancelled) return;

      if (Parent.Key<0) {
        throw new Exception($"Cannot store child DictionaryWithPropertyNameChild '{this}'.Parent to DictionaryWithPropertyNameParent '{Parent}' because parent is not stored yet.");
      }
      DC.Data._DictionaryWithPropertyNameChilds.Add(this);
      onStored();
    }
    partial void onStoring(ref bool isCancelled);
    partial void onStored();


    /// <summary>
    /// Estimated number of UTF8 characters needed to write DictionaryWithPropertyNameChild to CSV file
    /// </summary>
    public const int EstimatedLineLength = 23;


    /// <summary>
    /// Write DictionaryWithPropertyNameChild to CSV file
    /// </summary>
    internal static void Write(DictionaryWithPropertyNameChild dictionaryWithPropertyNameChild, CsvWriter csvWriter) {
      dictionaryWithPropertyNameChild.onCsvWrite();
      csvWriter.WriteDate(dictionaryWithPropertyNameChild.Date1);
      csvWriter.WriteDate(dictionaryWithPropertyNameChild.Date2);
      if (dictionaryWithPropertyNameChild.Parent.Key<0) throw new Exception($"Cannot write dictionaryWithPropertyNameChild '{dictionaryWithPropertyNameChild}' to CSV File, because Parent is not stored in DC.Data.DictionaryWithPropertyNameParents.");

      csvWriter.Write(dictionaryWithPropertyNameChild.Parent.Key.ToString());
    }
    partial void onCsvWrite();


    /// <summary>
    /// Updates DictionaryWithPropertyNameChild with the provided values
    /// </summary>
    public void Update(DateTime date1, DateTime date2, DictionaryWithPropertyNameParent parent) {
      if (Key>=0){
        if (parent.Key<0) {
          throw new Exception($"DictionaryWithPropertyNameChild.Update(): It is illegal to add stored DictionaryWithPropertyNameChild '{this}'" + Environment.NewLine + 
            $"to Parent '{parent}', which is not stored.");
        }
      }
      var clone = new DictionaryWithPropertyNameChild(this);
      var isCancelled = false;
      onUpdating(date1, date2, parent, ref isCancelled);
      if (isCancelled) return;


      //remove not yet updated item from parents which will be removed by update
      var hasParentChanged = Parent!=parent || Date1!=date1;
      if (hasParentChanged) {
        Parent.RemoveFromChildren(this);
      }

      //update properties and detect if any value has changed
      var isChangeDetected = false;
      var date1Rounded = date1.Floor(Rounding.Days);
      if (Date1!=date1Rounded) {
        Date1 = date1Rounded;
        isChangeDetected = true;
      }
      var date2Rounded = date2.Floor(Rounding.Days);
      if (Date2!=date2Rounded) {
        Date2 = date2Rounded;
        isChangeDetected = true;
      }
      if (Parent!=parent) {
        Parent = parent;
        isChangeDetected = true;
      }

      //add updated item to parents which have been newly added during update
      if (hasParentChanged) {
        Parent.AddToChildren(this);
      }
      if (isChangeDetected) {
        onUpdated(clone);
        if (Key>=0) {
          DC.Data._DictionaryWithPropertyNameChilds.ItemHasChanged(clone, this);
        } else if (DC.Data.IsTransaction) {
          DC.Data.AddTransaction(new TransactionItem(30, TransactionActivityEnum.Update, Key, this, oldItem: clone));
        }
        HasChanged?.Invoke(clone, this);
      }
    }
    partial void onUpdating(DateTime date1, DateTime date2, DictionaryWithPropertyNameParent parent, ref bool isCancelled);
    partial void onUpdated(DictionaryWithPropertyNameChild old);


    /// <summary>
    /// Updates this DictionaryWithPropertyNameChild with values from CSV file
    /// </summary>
    internal static void Update(DictionaryWithPropertyNameChild dictionaryWithPropertyNameChild, CsvReader csvReader){
      dictionaryWithPropertyNameChild.Date1 = csvReader.ReadDate();
      dictionaryWithPropertyNameChild.Date2 = csvReader.ReadDate();
        var parent = DC.Data._DictionaryWithPropertyNameParents.GetItem(csvReader.ReadInt())??
          DictionaryWithPropertyNameParent.NoDictionaryWithPropertyNameParent;
      if (dictionaryWithPropertyNameChild.Parent!=parent) {
        if (dictionaryWithPropertyNameChild.Parent!=DictionaryWithPropertyNameParent.NoDictionaryWithPropertyNameParent) {
          dictionaryWithPropertyNameChild.Parent.RemoveFromChildren(dictionaryWithPropertyNameChild);
        }
        dictionaryWithPropertyNameChild.Parent = parent;
        dictionaryWithPropertyNameChild.Parent.AddToChildren(dictionaryWithPropertyNameChild);
      }
      dictionaryWithPropertyNameChild.onCsvUpdate();
    }
    partial void onCsvUpdate();


    /// <summary>
    /// Removes DictionaryWithPropertyNameChild from DC.Data.DictionaryWithPropertyNameChilds.
    /// </summary>
    public void Release() {
      if (Key<0) {
        throw new Exception($"DictionaryWithPropertyNameChild.Release(): DictionaryWithPropertyNameChild '{this}' is not stored in DC.Data, key is {Key}.");
      }
      onReleasing();
      DC.Data._DictionaryWithPropertyNameChilds.Remove(Key);
      onReleased();
    }
    partial void onReleasing();
    partial void onReleased();


    /// <summary>
    /// Removes DictionaryWithPropertyNameChild from parents as part of a transaction rollback of the new() statement.
    /// </summary>
    internal static void RollbackItemNew(IStorageItem item) {
      var dictionaryWithPropertyNameChild = (DictionaryWithPropertyNameChild) item;
      if (dictionaryWithPropertyNameChild.Parent!=DictionaryWithPropertyNameParent.NoDictionaryWithPropertyNameParent) {
        dictionaryWithPropertyNameChild.Parent.RemoveFromChildren(dictionaryWithPropertyNameChild);
      }
      dictionaryWithPropertyNameChild.onRollbackItemNew();
    }
    partial void onRollbackItemNew();


    /// <summary>
    /// Releases DictionaryWithPropertyNameChild from DC.Data.DictionaryWithPropertyNameChilds as part of a transaction rollback of Store().
    /// </summary>
    internal static void RollbackItemStore(IStorageItem item) {
      var dictionaryWithPropertyNameChild = (DictionaryWithPropertyNameChild) item;
      dictionaryWithPropertyNameChild.onRollbackItemStored();
    }
    partial void onRollbackItemStored();


    /// <summary>
    /// Restores the DictionaryWithPropertyNameChild item data as it was before the last update as part of a transaction rollback.
    /// </summary>
    internal static void RollbackItemUpdate(IStorageItem oldStorageItem, IStorageItem newStorageItem) {
      var oldItem = (DictionaryWithPropertyNameChild) oldStorageItem;//an item clone with the values before item was updated
      var item = (DictionaryWithPropertyNameChild) newStorageItem;//is the instance whose values should be restored

      // remove updated item from parents
      var hasParentChanged = oldItem.Parent!=item.Parent || oldItem.Date1!=item.Date1;
      if (hasParentChanged) {
        item.Parent.RemoveFromChildren(item);
      }

      // updated item: restore old values
      item.Date1 = oldItem.Date1;
      item.Date2 = oldItem.Date2;
      item.Parent = oldItem.Parent;

      // add item with previous values to parents
      if (hasParentChanged) {
        item.Parent.AddToChildren(item);
      }
      item.onRollbackItemUpdated(oldItem);
    }
    partial void onRollbackItemUpdated(DictionaryWithPropertyNameChild oldDictionaryWithPropertyNameChild);


    /// <summary>
    /// Adds DictionaryWithPropertyNameChild to DC.Data.DictionaryWithPropertyNameChilds as part of a transaction rollback of Release().
    /// </summary>
    internal static void RollbackItemRelease(IStorageItem item) {
      var dictionaryWithPropertyNameChild = (DictionaryWithPropertyNameChild) item;
      dictionaryWithPropertyNameChild.onRollbackItemRelease();
    }
    partial void onRollbackItemRelease();


    /// <summary>
    /// Returns property values for tracing. Parents are shown with their key instead their content.
    /// </summary>
    public string ToTraceString() {
      var returnString =
        $"{this.GetKeyOrHash()}|" +
        $" {Date1.ToShortDateString()}|" +
        $" {Date2.ToShortDateString()}|" +
        $" Parent {Parent.GetKeyOrHash()}";
      onToTraceString(ref returnString);
      return returnString;
    }
    partial void onToTraceString(ref string returnString);


    /// <summary>
    /// Returns property values
    /// </summary>
    public string ToShortString() {
      var returnString =
        $"{Key.ToKeyString()}," +
        $" {Date1.ToShortDateString()}," +
        $" {Date2.ToShortDateString()}," +
        $" {Parent.ToShortString()}";
      onToShortString(ref returnString);
      return returnString;
    }
    partial void onToShortString(ref string returnString);


    /// <summary>
    /// Returns all property names and values
    /// </summary>
    public override string ToString() {
      var returnString =
        $"Key: {Key.ToKeyString()}," +
        $" Date1: {Date1.ToShortDateString()}," +
        $" Date2: {Date2.ToShortDateString()}," +
        $" Parent: {Parent.ToShortString()};";
      onToString(ref returnString);
      return returnString;
    }
    partial void onToString(ref string returnString);
    #endregion
  }
}
