//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by StorageClassGenerator
//
//     Do not change code in this file, it will get lost when the file gets 
//     auto generated again. Write your code into Dictionary1_MCParent.cs.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;
using System.Threading;
using StorageLib;


namespace DataModelSamples  {


  public partial class Dictionary1_MCParent: IStorageItemGeneric<Dictionary1_MCParent> {

    #region Properties
    //      ----------

    /// <summary>
    /// Unique identifier for Dictionary1_MCParent. Gets set once Dictionary1_MCParent gets added to DC.Data.
    /// </summary>
    public int Key { get; private set; }
    internal static void SetKey(IStorageItem dictionary1_MCParent, int key, bool _) {
      ((Dictionary1_MCParent)dictionary1_MCParent).Key = key;
    }


    public string Name { get; private set; }


    public IReadOnlyDictionary<DateTime, Dictionary1_MCChild> Children => children;
    readonly Dictionary<DateTime, Dictionary1_MCChild> children;


    /// <summary>
    /// Headers written to first line in CSV file
    /// </summary>
    internal static readonly string[] Headers = {"Key", "Name"};


    /// <summary>
    /// None existing Dictionary1_MCParent
    /// </summary>
    internal static Dictionary1_MCParent NoDictionary1_MCParent = new Dictionary1_MCParent("NoName", isStoring: false);
    #endregion


    #region Events
    //      ------

    /// <summary>
    /// Content of Dictionary1_MCParent has changed. Gets only raised for changes occurring after loading DC.Data with previously stored data.
    /// </summary>
    public event Action</*old*/Dictionary1_MCParent, /*new*/Dictionary1_MCParent>? HasChanged;
    #endregion


    #region Constructors
    //      ------------

    /// <summary>
    /// Dictionary1_MCParent Constructor. If isStoring is true, adds Dictionary1_MCParent to DC.Data.Dictionary1_MCParents.
    /// </summary>
    public Dictionary1_MCParent(string name, bool isStoring = true) {
      Key = StorageExtensions.NoKey;
      Name = name;
      children = new Dictionary<DateTime, Dictionary1_MCChild>();
      onConstruct();
      if (DC.Data.IsTransaction) {
        DC.Data.AddTransaction(new TransactionItem(7,TransactionActivityEnum.New, Key, this));
      }

      if (isStoring) {
        Store();
      }
    }
    partial void onConstruct();


    /// <summary>
    /// Cloning constructor. It will copy all data from original except any collection (children).
    /// </summary>
    #pragma warning disable CS8618 // Children collections are uninitialized.
    public Dictionary1_MCParent(Dictionary1_MCParent original) {
    #pragma warning restore CS8618 //
      Key = StorageExtensions.NoKey;
      Name = original.Name;
      onCloned(this);
    }
    partial void onCloned(Dictionary1_MCParent clone);


    /// <summary>
    /// Constructor for Dictionary1_MCParent read from CSV file
    /// </summary>
    private Dictionary1_MCParent(int key, CsvReader csvReader){
      Key = key;
      Name = csvReader.ReadString();
      children = new Dictionary<DateTime, Dictionary1_MCChild>();
      onCsvConstruct();
    }
    partial void onCsvConstruct();


    /// <summary>
    /// New Dictionary1_MCParent read from CSV file
    /// </summary>
    internal static Dictionary1_MCParent Create(int key, CsvReader csvReader) {
      return new Dictionary1_MCParent(key, csvReader);
    }
    #endregion


    #region Methods
    //      -------

    /// <summary>
    /// Adds Dictionary1_MCParent to DC.Data.Dictionary1_MCParents.<br/>
    /// Throws an Exception when Dictionary1_MCParent is already stored.
    /// </summary>
    public void Store() {
      if (Key>=0) {
        throw new Exception($"Dictionary1_MCParent cannot be stored again in DC.Data, key {Key} is greater equal 0." + Environment.NewLine + ToString());
      }

      var isCancelled = false;
      onStoring(ref isCancelled);
      if (isCancelled) return;

      DC.Data._Dictionary1_MCParents.Add(this);
      onStored();
    }
    partial void onStoring(ref bool isCancelled);
    partial void onStored();


    /// <summary>
    /// Estimated number of UTF8 characters needed to write Dictionary1_MCParent to CSV file
    /// </summary>
    public const int EstimatedLineLength = 150;


    /// <summary>
    /// Write Dictionary1_MCParent to CSV file
    /// </summary>
    internal static void Write(Dictionary1_MCParent dictionary1_MCParent, CsvWriter csvWriter) {
      dictionary1_MCParent.onCsvWrite();
      csvWriter.Write(dictionary1_MCParent.Name);
    }
    partial void onCsvWrite();


    /// <summary>
    /// Updates Dictionary1_MCParent with the provided values
    /// </summary>
    public void Update(string name) {
      var clone = new Dictionary1_MCParent(this);
      var isCancelled = false;
      onUpdating(name, ref isCancelled);
      if (isCancelled) return;


      //update properties and detect if any value has changed
      var isChangeDetected = false;
      if (Name!=name) {
        Name = name;
        isChangeDetected = true;
      }
      if (isChangeDetected) {
        onUpdated(clone);
        if (Key>=0) {
          DC.Data._Dictionary1_MCParents.ItemHasChanged(clone, this);
        } else if (DC.Data.IsTransaction) {
          DC.Data.AddTransaction(new TransactionItem(7, TransactionActivityEnum.Update, Key, this, oldItem: clone));
        }
        HasChanged?.Invoke(clone, this);
      }
    }
    partial void onUpdating(string name, ref bool isCancelled);
    partial void onUpdated(Dictionary1_MCParent old);


    /// <summary>
    /// Updates this Dictionary1_MCParent with values from CSV file
    /// </summary>
    internal static void Update(Dictionary1_MCParent dictionary1_MCParent, CsvReader csvReader){
      dictionary1_MCParent.Name = csvReader.ReadString();
      dictionary1_MCParent.onCsvUpdate();
    }
    partial void onCsvUpdate();


    /// <summary>
    /// Add dictionary1_MCChild to Children.
    /// </summary>
    internal void AddToChildren(Dictionary1_MCChild dictionary1_MCChild) {
#if DEBUG
      if (dictionary1_MCChild==Dictionary1_MCChild.NoDictionary1_MCChild) throw new Exception();
      if ((dictionary1_MCChild.Key>=0)&&(Key<0)) throw new Exception();
      if (children.ContainsKey(dictionary1_MCChild.Date)) throw new Exception();
#endif
      children.Add(dictionary1_MCChild.Date, dictionary1_MCChild);
      onAddedToChildren(dictionary1_MCChild);
    }
    partial void onAddedToChildren(Dictionary1_MCChild dictionary1_MCChild);


    /// <summary>
    /// Removes dictionary1_MCChild from Dictionary1_MCParent.
    /// </summary>
    internal void RemoveFromChildren(Dictionary1_MCChild dictionary1_MCChild) {
#if DEBUG
      if (!children.Remove(dictionary1_MCChild.Date)) throw new Exception();
#else
        children.Remove(dictionary1_MCChild.Date);
#endif
      onRemovedFromChildren(dictionary1_MCChild);
    }
    partial void onRemovedFromChildren(Dictionary1_MCChild dictionary1_MCChild);


    /// <summary>
    /// Removes Dictionary1_MCParent from DC.Data.Dictionary1_MCParents.
    /// </summary>
    public void Release() {
      if (Key<0) {
        throw new Exception($"Dictionary1_MCParent.Release(): Dictionary1_MCParent '{this}' is not stored in DC.Data, key is {Key}.");
      }
      foreach (var dictionary1_MCChild in Children.Values) {
        if (dictionary1_MCChild?.Key>=0) {
          throw new Exception($"Cannot release Dictionary1_MCParent '{this}' " + Environment.NewLine + 
            $"because '{dictionary1_MCChild}' in Dictionary1_MCParent.Children is still stored.");
        }
      }
      onReleased();
      DC.Data._Dictionary1_MCParents.Remove(Key);
    }
    partial void onReleased();


    /// <summary>
    /// Undoes the new() statement as part of a transaction rollback.
    /// </summary>
    internal static void RollbackItemNew(IStorageItem item) {
      var dictionary1_MCParent = (Dictionary1_MCParent) item;
      dictionary1_MCParent.onRollbackItemNew();
    }
    partial void onRollbackItemNew();


    /// <summary>
    /// Releases Dictionary1_MCParent from DC.Data.Dictionary1_MCParents as part of a transaction rollback of Store().
    /// </summary>
    internal static void RollbackItemStore(IStorageItem item) {
      var dictionary1_MCParent = (Dictionary1_MCParent) item;
      dictionary1_MCParent.onRollbackItemStored();
    }
    partial void onRollbackItemStored();


    /// <summary>
    /// Restores the Dictionary1_MCParent item data as it was before the last update as part of a transaction rollback.
    /// </summary>
    internal static void RollbackItemUpdate(IStorageItem oldStorageItem, IStorageItem newStorageItem) {
      var oldItem = (Dictionary1_MCParent) oldStorageItem;//an item clone with the values before item was updated
      var item = (Dictionary1_MCParent) newStorageItem;//is the instance whose values should be restored

      // updated item: restore old values
      item.Name = oldItem.Name;
      item.onRollbackItemUpdated(oldItem);
    }
    partial void onRollbackItemUpdated(Dictionary1_MCParent oldDictionary1_MCParent);


    /// <summary>
    /// Adds Dictionary1_MCParent to DC.Data.Dictionary1_MCParents as part of a transaction rollback of Release().
    /// </summary>
    internal static void RollbackItemRelease(IStorageItem item) {
      var dictionary1_MCParent = (Dictionary1_MCParent) item;
      dictionary1_MCParent.onRollbackItemRelease();
    }
    partial void onRollbackItemRelease();


    /// <summary>
    /// Returns property values for tracing. Parents are shown with their key instead their content.
    /// </summary>
    public string ToTraceString() {
      var returnString =
        $"{this.GetKeyOrHash()}|" +
        $" {Name}";
      onToTraceString(ref returnString);
      return returnString;
    }
    partial void onToTraceString(ref string returnString);


    /// <summary>
    /// Returns property values
    /// </summary>
    public string ToShortString() {
      var returnString =
        $"{Key.ToKeyString()}," +
        $" {Name}";
      onToShortString(ref returnString);
      return returnString;
    }
    partial void onToShortString(ref string returnString);


    /// <summary>
    /// Returns all property names and values
    /// </summary>
    public override string ToString() {
      var returnString =
        $"Key: {Key.ToKeyString()}," +
        $" Name: {Name}," +
        $" Children: {Children.Count};";
      onToString(ref returnString);
      return returnString;
    }
    partial void onToString(ref string returnString);
    #endregion
  }
}
