//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by StorageClassGenerator
//
//     Do not change code in this file, it will get lost when the file gets 
//     auto generated again. Write your code into NoneUpdateableReleasableClass.cs.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;
using System.Threading;
using StorageLib;


namespace DataModelSamples  {


  public partial class NoneUpdateableReleasableClass: IStorageItem<NoneUpdateableReleasableClass> {

    #region Properties
    //      ----------

    /// <summary>
    /// Unique identifier for NoneUpdateableReleasableClass. Gets set once NoneUpdateableReleasableClass gets added to DC.Data.
    /// </summary>
    public int Key { get; private set; }
    internal static void SetKey(IStorageItem noneUpdateableReleasableClass, int key, bool _) {
      ((NoneUpdateableReleasableClass)noneUpdateableReleasableClass).Key = key;
    }


    public string Name { get; }


    /// <summary>
    /// Headers written to first line in CSV file
    /// </summary>
    internal static readonly string[] Headers = {"Key", "Name"};


    /// <summary>
    /// None existing NoneUpdateableReleasableClass, used as a temporary place holder when reading a CSV file
    /// which was not compacted. It might create first a later deleted item linking to a 
    /// deleted parent. In this case, the parent property gets set to NoNoneUpdateableReleasableClass. Once the CSV
    /// file is completely read, that child will actually be deleted (released) and Verify()
    /// ensures that there are no stored children with links to NoNoneUpdateableReleasableClass.
    /// </summary>
    internal static NoneUpdateableReleasableClass NoNoneUpdateableReleasableClass = new NoneUpdateableReleasableClass("NoName", isStoring: false);
    #endregion


    #region Events
    //      ------

    /// <summary>
    /// This event will never be raised, but is needed to comply with IStorage.
    /// </summary>
#pragma warning disable 67
    public event Action</*old*/NoneUpdateableReleasableClass, /*new*/NoneUpdateableReleasableClass>? HasChanged;
#pragma warning restore 67
    #endregion


    #region Constructors
    //      ------------

    /// <summary>
    /// NoneUpdateableReleasableClass Constructor. If isStoring is true, adds NoneUpdateableReleasableClass to DC.Data.NoneUpdateableReleasableClasss.
    /// </summary>
    public NoneUpdateableReleasableClass(string name, bool isStoring = true) {
      Key = StorageExtensions.NoKey;
      Name = name;
      onConstruct();
      if (DC.Data.IsTransaction) {
        DC.Data.AddTransaction(new TransactionItem(2,TransactionActivityEnum.New, Key, this));
      }

      if (isStoring) {
        Store();
      }
    }
    partial void onConstruct();


    /// <summary>
    /// Cloning constructor. It will copy all data from original except any collection (children).
    /// </summary>
    #pragma warning disable CS8618 // Children collections are uninitialized.
    public NoneUpdateableReleasableClass(NoneUpdateableReleasableClass original) {
    #pragma warning restore CS8618 //
      Key = StorageExtensions.NoKey;
      Name = original.Name;
      onCloned(this);
    }
    partial void onCloned(NoneUpdateableReleasableClass clone);


    /// <summary>
    /// Constructor for NoneUpdateableReleasableClass read from CSV file
    /// </summary>
    private NoneUpdateableReleasableClass(int key, CsvReader csvReader){
      Key = key;
      Name = csvReader.ReadString();
      onCsvConstruct();
    }
    partial void onCsvConstruct();


    /// <summary>
    /// New NoneUpdateableReleasableClass read from CSV file
    /// </summary>
    internal static NoneUpdateableReleasableClass Create(int key, CsvReader csvReader) {
      return new NoneUpdateableReleasableClass(key, csvReader);
    }
    #endregion


    #region Methods
    //      -------

    /// <summary>
    /// Adds NoneUpdateableReleasableClass to DC.Data.NoneUpdateableReleasableClasss.<br/>
    /// Throws an Exception when NoneUpdateableReleasableClass is already stored.
    /// </summary>
    public void Store() {
      if (Key>=0) {
        throw new Exception($"NoneUpdateableReleasableClass cannot be stored again in DC.Data, key {Key} is greater equal 0." + Environment.NewLine + ToString());
      }

      var isCancelled = false;
      onStoring(ref isCancelled);
      if (isCancelled) return;

      DC.Data._NoneUpdateableReleasableClasss.Add(this);
      onStored();
    }
    partial void onStoring(ref bool isCancelled);
    partial void onStored();


    /// <summary>
    /// Estimated number of UTF8 characters needed to write NoneUpdateableReleasableClass to CSV file
    /// </summary>
    public const int EstimatedLineLength = 150;


    /// <summary>
    /// Write NoneUpdateableReleasableClass to CSV file
    /// </summary>
    internal static void Write(NoneUpdateableReleasableClass noneUpdateableReleasableClass, CsvWriter csvWriter) {
      noneUpdateableReleasableClass.onCsvWrite();
      csvWriter.Write(noneUpdateableReleasableClass.Name);
    }
    partial void onCsvWrite();


    /// <summary>
    /// Removes NoneUpdateableReleasableClass from DC.Data.NoneUpdateableReleasableClasss.
    /// </summary>
    public void Release() {
      if (Key<0) {
        throw new Exception($"NoneUpdateableReleasableClass.Release(): NoneUpdateableReleasableClass '{this}' is not stored in DC.Data, key is {Key}.");
      }
      DC.Data._NoneUpdateableReleasableClasss.Remove(Key);
      onReleased();
    }
    partial void onReleased();


    /// <summary>
    /// Undoes the new() statement as part of a transaction rollback.
    /// </summary>
    internal static void RollbackItemNew(IStorageItem item) {
      var noneUpdateableReleasableClass = (NoneUpdateableReleasableClass) item;
      noneUpdateableReleasableClass.onRollbackItemNew();
    }
    partial void onRollbackItemNew();


    /// <summary>
    /// Releases NoneUpdateableReleasableClass from DC.Data.NoneUpdateableReleasableClasss as part of a transaction rollback of Store().
    /// </summary>
    internal static void RollbackItemStore(IStorageItem item) {
      var noneUpdateableReleasableClass = (NoneUpdateableReleasableClass) item;
      noneUpdateableReleasableClass.onRollbackItemStored();
    }
    partial void onRollbackItemStored();


    /// <summary>
    /// Restores the NoneUpdateableReleasableClass item data as it was before the last update as part of a transaction rollback.
    /// </summary>
    internal static void RollbackItemUpdate(IStorageItem oldStorageItem, IStorageItem newStorageItem) {
      var oldItem = (NoneUpdateableReleasableClass) oldStorageItem;//an item clone with the values before item was updated
      var item = (NoneUpdateableReleasableClass) newStorageItem;//is the instance whose values should be restored

      // if possible, throw exceptions before changing anything
      if (item.Name!=oldItem.Name) {
        throw new Exception($"NoneUpdateableReleasableClass.Update(): Property Name '{item.Name}' is " +
          $"readonly, Name '{oldItem.Name}' should be the same." + Environment.NewLine + 
          item.ToString());
      }

      // updated item: restore old values
      item.onRollbackItemUpdated(oldItem);
    }
    partial void onRollbackItemUpdated(NoneUpdateableReleasableClass oldNoneUpdateableReleasableClass);


    /// <summary>
    /// Adds NoneUpdateableReleasableClass to DC.Data.NoneUpdateableReleasableClasss as part of a transaction rollback of Release().
    /// </summary>
    internal static void RollbackItemRelease(IStorageItem item) {
      var noneUpdateableReleasableClass = (NoneUpdateableReleasableClass) item;
      noneUpdateableReleasableClass.onRollbackItemRelease();
    }
    partial void onRollbackItemRelease();


    /// <summary>
    /// Returns property values for tracing. Parents are shown with their key instead their content.
    /// </summary>
    public string ToTraceString() {
      var returnString =
        $"{this.GetKeyOrHash()}|" +
        $" {Name}";
      onToTraceString(ref returnString);
      return returnString;
    }
    partial void onToTraceString(ref string returnString);


    /// <summary>
    /// Returns property values
    /// </summary>
    public string ToShortString() {
      var returnString =
        $"{Key.ToKeyString()}," +
        $" {Name}";
      onToShortString(ref returnString);
      return returnString;
    }
    partial void onToShortString(ref string returnString);


    /// <summary>
    /// Returns all property names and values
    /// </summary>
    public override string ToString() {
      var returnString =
        $"Key: {Key.ToKeyString()}," +
        $" Name: {Name};";
      onToString(ref returnString);
      return returnString;
    }
    partial void onToString(ref string returnString);
    #endregion
  }
}
