//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by StorageClassGenerator
//
//     Do not change code in this file, it will get lost when the file gets 
//     auto generated again. Write your code into SortedListChild.cs.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;
using System.Threading;
using StorageLib;


namespace DataModelSamples  {


  public partial class SortedListChild: IStorageItemGeneric<SortedListChild> {

    #region Properties
    //      ----------

    /// <summary>
    /// Unique identifier for SortedListChild. Gets set once SortedListChild gets added to DC.Data.
    /// </summary>
    public int Key { get; private set; }
    internal static void SetKey(IStorageItem sortedListChild, int key, bool _) {
      ((SortedListChild)sortedListChild).Key = key;
    }


    public string Name { get; private set; }


    public SortedListParent Parent { get; private set; }


    /// <summary>
    /// Headers written to first line in CSV file
    /// </summary>
    internal static readonly string[] Headers = {"Key", "Name", "Parent"};


    /// <summary>
    /// None existing SortedListChild
    /// </summary>
    internal static SortedListChild NoSortedListChild = new SortedListChild("NoName", SortedListParent.NoSortedListParent, isStoring: false);
    #endregion


    #region Events
    //      ------

    /// <summary>
    /// Content of SortedListChild has changed. Gets only raised for changes occurring after loading DC.Data with previously stored data.
    /// </summary>
    public event Action</*old*/SortedListChild, /*new*/SortedListChild>? HasChanged;
    #endregion


    #region Constructors
    //      ------------

    /// <summary>
    /// SortedListChild Constructor. If isStoring is true, adds SortedListChild to DC.Data.SortedListChilds.
    /// </summary>
    public SortedListChild(string name, SortedListParent parent, bool isStoring = true) {
      Key = StorageExtensions.NoKey;
      Name = name;
      Parent = parent;
      Parent.AddToChildren(this);
      onConstruct();
      if (DC.Data.IsTransaction) {
        DC.Data.AddTransaction(new TransactionItem(8,TransactionActivityEnum.New, Key, this));
      }

      if (isStoring) {
        Store();
      }
    }
    partial void onConstruct();


    /// <summary>
    /// Cloning constructor. It will copy all data from original except any collection (children).
    /// </summary>
    #pragma warning disable CS8618 // Children collections are uninitialized.
    public SortedListChild(SortedListChild original) {
    #pragma warning restore CS8618 //
      Key = StorageExtensions.NoKey;
      Name = original.Name;
      Parent = original.Parent;
      onCloned(this);
    }
    partial void onCloned(SortedListChild clone);


    /// <summary>
    /// Constructor for SortedListChild read from CSV file
    /// </summary>
    private SortedListChild(int key, CsvReader csvReader){
      Key = key;
      Name = csvReader.ReadString();
      var sortedListParentKey = csvReader.ReadInt();
      Parent = DC.Data._SortedListParents.GetItem(sortedListParentKey)??
        throw new Exception($"Read SortedListChild from CSV file: Cannot find Parent with key {sortedListParentKey}." + Environment.NewLine + 
          csvReader.PresentContent);
      if (Parent!=SortedListParent.NoSortedListParent) {
        Parent.AddToChildren(this);
      }
      onCsvConstruct();
    }
    partial void onCsvConstruct();


    /// <summary>
    /// New SortedListChild read from CSV file
    /// </summary>
    internal static SortedListChild Create(int key, CsvReader csvReader) {
      return new SortedListChild(key, csvReader);
    }


    /// <summary>
    /// Verify that sortedListChild.Parent exists.
    /// </summary>
    internal static bool Verify(SortedListChild sortedListChild) {
      if (sortedListChild.Parent==SortedListParent.NoSortedListParent) return false;
      return true;
    }
    #endregion


    #region Methods
    //      -------

    /// <summary>
    /// Adds SortedListChild to DC.Data.SortedListChilds.<br/>
    /// Throws an Exception when SortedListChild is already stored.
    /// </summary>
    public void Store() {
      if (Key>=0) {
        throw new Exception($"SortedListChild cannot be stored again in DC.Data, key {Key} is greater equal 0." + Environment.NewLine + ToString());
      }

      var isCancelled = false;
      onStoring(ref isCancelled);
      if (isCancelled) return;

      if (Parent.Key<0) {
        throw new Exception($"Cannot store child SortedListChild '{this}'.Parent to SortedListParent '{Parent}' because parent is not stored yet.");
      }
      DC.Data._SortedListChilds.Add(this);
      onStored();
    }
    partial void onStoring(ref bool isCancelled);
    partial void onStored();


    /// <summary>
    /// Estimated number of UTF8 characters needed to write SortedListChild to CSV file
    /// </summary>
    public const int EstimatedLineLength = 150;


    /// <summary>
    /// Write SortedListChild to CSV file
    /// </summary>
    internal static void Write(SortedListChild sortedListChild, CsvWriter csvWriter) {
      sortedListChild.onCsvWrite();
      csvWriter.Write(sortedListChild.Name);
      if (sortedListChild.Parent.Key<0) throw new Exception($"Cannot write sortedListChild '{sortedListChild}' to CSV File, because Parent is not stored in DC.Data.SortedListParents.");

      csvWriter.Write(sortedListChild.Parent.Key.ToString());
    }
    partial void onCsvWrite();


    /// <summary>
    /// Updates SortedListChild with the provided values
    /// </summary>
    public void Update(string name, SortedListParent parent) {
      if (Key>=0){
        if (parent.Key<0) {
          throw new Exception($"SortedListChild.Update(): It is illegal to add stored SortedListChild '{this}'" + Environment.NewLine + 
            $"to Parent '{parent}', which is not stored.");
        }
      }
      var clone = new SortedListChild(this);
      var isCancelled = false;
      onUpdating(name, parent, ref isCancelled);
      if (isCancelled) return;


      //remove not yet updated item from parents which will be removed by update
      var hasParentChanged = Parent!=parent || Name!=name;
      if (hasParentChanged) {
        Parent.RemoveFromChildren(this);
      }

      //update properties and detect if any value has changed
      var isChangeDetected = false;
      if (Name!=name) {
        Name = name;
        isChangeDetected = true;
      }
      if (Parent!=parent) {
        Parent = parent;
        isChangeDetected = true;
      }

      //add updated item to parents which have been newly added during update
      if (hasParentChanged) {
        Parent.AddToChildren(this);
      }
      if (isChangeDetected) {
        onUpdated(clone);
        if (Key>=0) {
          DC.Data._SortedListChilds.ItemHasChanged(clone, this);
        } else if (DC.Data.IsTransaction) {
          DC.Data.AddTransaction(new TransactionItem(8, TransactionActivityEnum.Update, Key, this, oldItem: clone));
        }
        HasChanged?.Invoke(clone, this);
      }
    }
    partial void onUpdating(string name, SortedListParent parent, ref bool isCancelled);
    partial void onUpdated(SortedListChild old);


    /// <summary>
    /// Updates this SortedListChild with values from CSV file
    /// </summary>
    internal static void Update(SortedListChild sortedListChild, CsvReader csvReader){
      sortedListChild.Name = csvReader.ReadString();
        var parent = DC.Data._SortedListParents.GetItem(csvReader.ReadInt())??
          SortedListParent.NoSortedListParent;
      if (sortedListChild.Parent!=parent) {
        if (sortedListChild.Parent!=SortedListParent.NoSortedListParent) {
          sortedListChild.Parent.RemoveFromChildren(sortedListChild);
        }
        sortedListChild.Parent = parent;
        sortedListChild.Parent.AddToChildren(sortedListChild);
      }
      sortedListChild.onCsvUpdate();
    }
    partial void onCsvUpdate();


    /// <summary>
    /// Removes SortedListChild from DC.Data.SortedListChilds.
    /// </summary>
    public void Release() {
      if (Key<0) {
        throw new Exception($"SortedListChild.Release(): SortedListChild '{this}' is not stored in DC.Data, key is {Key}.");
      }
      onReleased();
      DC.Data._SortedListChilds.Remove(Key);
    }
    partial void onReleased();


    /// <summary>
    /// Removes SortedListChild from parents as part of a transaction rollback of the new() statement.
    /// </summary>
    internal static void RollbackItemNew(IStorageItem item) {
      var sortedListChild = (SortedListChild) item;
      if (sortedListChild.Parent!=SortedListParent.NoSortedListParent) {
        sortedListChild.Parent.RemoveFromChildren(sortedListChild);
      }
      sortedListChild.onRollbackItemNew();
    }
    partial void onRollbackItemNew();


    /// <summary>
    /// Releases SortedListChild from DC.Data.SortedListChilds as part of a transaction rollback of Store().
    /// </summary>
    internal static void RollbackItemStore(IStorageItem item) {
      var sortedListChild = (SortedListChild) item;
      sortedListChild.onRollbackItemStored();
    }
    partial void onRollbackItemStored();


    /// <summary>
    /// Restores the SortedListChild item data as it was before the last update as part of a transaction rollback.
    /// </summary>
    internal static void RollbackItemUpdate(IStorageItem oldStorageItem, IStorageItem newStorageItem) {
      var oldItem = (SortedListChild) oldStorageItem;//an item clone with the values before item was updated
      var item = (SortedListChild) newStorageItem;//is the instance whose values should be restored

      // remove updated item from parents
      var hasParentChanged = oldItem.Parent!=item.Parent || oldItem.Name!=item.Name;
      if (hasParentChanged) {
        item.Parent.RemoveFromChildren(item);
      }

      // updated item: restore old values
      item.Name = oldItem.Name;
      item.Parent = oldItem.Parent;

      // add item with previous values to parents
      if (hasParentChanged) {
        item.Parent.AddToChildren(item);
      }
      item.onRollbackItemUpdated(oldItem);
    }
    partial void onRollbackItemUpdated(SortedListChild oldSortedListChild);


    /// <summary>
    /// Adds SortedListChild to DC.Data.SortedListChilds as part of a transaction rollback of Release().
    /// </summary>
    internal static void RollbackItemRelease(IStorageItem item) {
      var sortedListChild = (SortedListChild) item;
      sortedListChild.onRollbackItemRelease();
    }
    partial void onRollbackItemRelease();


    /// <summary>
    /// Returns property values for tracing. Parents are shown with their key instead their content.
    /// </summary>
    public string ToTraceString() {
      var returnString =
        $"{this.GetKeyOrHash()}|" +
        $" {Name}|" +
        $" Parent {Parent.GetKeyOrHash()}";
      onToTraceString(ref returnString);
      return returnString;
    }
    partial void onToTraceString(ref string returnString);


    /// <summary>
    /// Returns property values
    /// </summary>
    public string ToShortString() {
      var returnString =
        $"{Key.ToKeyString()}," +
        $" {Name}," +
        $" {Parent.ToShortString()}";
      onToShortString(ref returnString);
      return returnString;
    }
    partial void onToShortString(ref string returnString);


    /// <summary>
    /// Returns all property names and values
    /// </summary>
    public override string ToString() {
      var returnString =
        $"Key: {Key.ToKeyString()}," +
        $" Name: {Name}," +
        $" Parent: {Parent.ToShortString()};";
      onToString(ref returnString);
      return returnString;
    }
    partial void onToString(ref string returnString);
    #endregion
  }
}
