//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by StorageClassGenerator
//
//     Do not change code in this file, it will get lost when the file gets 
//     auto generated again. Write your code into SortedList1_MCParent.cs.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;
using System.Threading;
using StorageLib;


namespace DataModelSamples  {


  public partial class SortedList1_MCParent: IStorageItemGeneric<SortedList1_MCParent> {

    #region Properties
    //      ----------

    /// <summary>
    /// Unique identifier for SortedList1_MCParent. Gets set once SortedList1_MCParent gets added to DC.Data.
    /// </summary>
    public int Key { get; private set; }
    internal static void SetKey(IStorageItem sortedList1_MCParent, int key, bool _) {
      ((SortedList1_MCParent)sortedList1_MCParent).Key = key;
    }


    public string Name { get; private set; }


    public IReadOnlyDictionary<string, SortedList1_MCChild> Children => children;
    readonly SortedList<string, SortedList1_MCChild> children;


    /// <summary>
    /// Headers written to first line in CSV file
    /// </summary>
    internal static readonly string[] Headers = {"Key", "Name"};


    /// <summary>
    /// None existing SortedList1_MCParent
    /// </summary>
    internal static SortedList1_MCParent NoSortedList1_MCParent = new SortedList1_MCParent("NoName", isStoring: false);
    #endregion


    #region Events
    //      ------

    /// <summary>
    /// Content of SortedList1_MCParent has changed. Gets only raised for changes occurring after loading DC.Data with previously stored data.
    /// </summary>
    public event Action</*old*/SortedList1_MCParent, /*new*/SortedList1_MCParent>? HasChanged;
    #endregion


    #region Constructors
    //      ------------

    /// <summary>
    /// SortedList1_MCParent Constructor. If isStoring is true, adds SortedList1_MCParent to DC.Data.SortedList1_MCParents.
    /// </summary>
    public SortedList1_MCParent(string name, bool isStoring = true) {
      Key = StorageExtensions.NoKey;
      Name = name;
      children = new SortedList<string, SortedList1_MCChild>();
      onConstruct();
      if (DC.Data.IsTransaction) {
        DC.Data.AddTransaction(new TransactionItem(13,TransactionActivityEnum.New, Key, this));
      }

      if (isStoring) {
        Store();
      }
    }
    partial void onConstruct();


    /// <summary>
    /// Cloning constructor. It will copy all data from original except any collection (children).
    /// </summary>
    #pragma warning disable CS8618 // Children collections are uninitialized.
    public SortedList1_MCParent(SortedList1_MCParent original) {
    #pragma warning restore CS8618 //
      Key = StorageExtensions.NoKey;
      Name = original.Name;
      onCloned(this);
    }
    partial void onCloned(SortedList1_MCParent clone);


    /// <summary>
    /// Constructor for SortedList1_MCParent read from CSV file
    /// </summary>
    private SortedList1_MCParent(int key, CsvReader csvReader){
      Key = key;
      Name = csvReader.ReadString();
      children = new SortedList<string, SortedList1_MCChild>();
      onCsvConstruct();
    }
    partial void onCsvConstruct();


    /// <summary>
    /// New SortedList1_MCParent read from CSV file
    /// </summary>
    internal static SortedList1_MCParent Create(int key, CsvReader csvReader) {
      return new SortedList1_MCParent(key, csvReader);
    }
    #endregion


    #region Methods
    //      -------

    /// <summary>
    /// Adds SortedList1_MCParent to DC.Data.SortedList1_MCParents.<br/>
    /// Throws an Exception when SortedList1_MCParent is already stored.
    /// </summary>
    public void Store() {
      if (Key>=0) {
        throw new Exception($"SortedList1_MCParent cannot be stored again in DC.Data, key {Key} is greater equal 0." + Environment.NewLine + ToString());
      }

      var isCancelled = false;
      onStoring(ref isCancelled);
      if (isCancelled) return;

      DC.Data._SortedList1_MCParents.Add(this);
      onStored();
    }
    partial void onStoring(ref bool isCancelled);
    partial void onStored();


    /// <summary>
    /// Estimated number of UTF8 characters needed to write SortedList1_MCParent to CSV file
    /// </summary>
    public const int EstimatedLineLength = 150;


    /// <summary>
    /// Write SortedList1_MCParent to CSV file
    /// </summary>
    internal static void Write(SortedList1_MCParent sortedList1_MCParent, CsvWriter csvWriter) {
      sortedList1_MCParent.onCsvWrite();
      csvWriter.Write(sortedList1_MCParent.Name);
    }
    partial void onCsvWrite();


    /// <summary>
    /// Updates SortedList1_MCParent with the provided values
    /// </summary>
    public void Update(string name) {
      var clone = new SortedList1_MCParent(this);
      var isCancelled = false;
      onUpdating(name, ref isCancelled);
      if (isCancelled) return;


      //update properties and detect if any value has changed
      var isChangeDetected = false;
      if (Name!=name) {
        Name = name;
        isChangeDetected = true;
      }
      if (isChangeDetected) {
        onUpdated(clone);
        if (Key>=0) {
          DC.Data._SortedList1_MCParents.ItemHasChanged(clone, this);
        } else if (DC.Data.IsTransaction) {
          DC.Data.AddTransaction(new TransactionItem(13, TransactionActivityEnum.Update, Key, this, oldItem: clone));
        }
        HasChanged?.Invoke(clone, this);
      }
    }
    partial void onUpdating(string name, ref bool isCancelled);
    partial void onUpdated(SortedList1_MCParent old);


    /// <summary>
    /// Updates this SortedList1_MCParent with values from CSV file
    /// </summary>
    internal static void Update(SortedList1_MCParent sortedList1_MCParent, CsvReader csvReader){
      sortedList1_MCParent.Name = csvReader.ReadString();
      sortedList1_MCParent.onCsvUpdate();
    }
    partial void onCsvUpdate();


    /// <summary>
    /// Add sortedList1_MCChild to Children.
    /// </summary>
    internal void AddToChildren(SortedList1_MCChild sortedList1_MCChild) {
#if DEBUG
      if (sortedList1_MCChild==SortedList1_MCChild.NoSortedList1_MCChild) throw new Exception();
      if ((sortedList1_MCChild.Key>=0)&&(Key<0)) throw new Exception();
      if (children.ContainsKey(sortedList1_MCChild.Name)) throw new Exception();
#endif
      children.Add(sortedList1_MCChild.Name, sortedList1_MCChild);
      onAddedToChildren(sortedList1_MCChild);
    }
    partial void onAddedToChildren(SortedList1_MCChild sortedList1_MCChild);


    /// <summary>
    /// Removes sortedList1_MCChild from SortedList1_MCParent.
    /// </summary>
    internal void RemoveFromChildren(SortedList1_MCChild sortedList1_MCChild) {
#if DEBUG
      if (!children.Remove(sortedList1_MCChild.Name)) throw new Exception();
#else
        children.Remove(sortedList1_MCChild.Name);
#endif
      onRemovedFromChildren(sortedList1_MCChild);
    }
    partial void onRemovedFromChildren(SortedList1_MCChild sortedList1_MCChild);


    /// <summary>
    /// Removes SortedList1_MCParent from DC.Data.SortedList1_MCParents.
    /// </summary>
    public void Release() {
      if (Key<0) {
        throw new Exception($"SortedList1_MCParent.Release(): SortedList1_MCParent '{this}' is not stored in DC.Data, key is {Key}.");
      }
      foreach (var sortedList1_MCChild in Children.Values) {
        if (sortedList1_MCChild?.Key>=0) {
          throw new Exception($"Cannot release SortedList1_MCParent '{this}' " + Environment.NewLine + 
            $"because '{sortedList1_MCChild}' in SortedList1_MCParent.Children is still stored.");
        }
      }
      onReleased();
      DC.Data._SortedList1_MCParents.Remove(Key);
    }
    partial void onReleased();


    /// <summary>
    /// Undoes the new() statement as part of a transaction rollback.
    /// </summary>
    internal static void RollbackItemNew(IStorageItem item) {
      var sortedList1_MCParent = (SortedList1_MCParent) item;
      sortedList1_MCParent.onRollbackItemNew();
    }
    partial void onRollbackItemNew();


    /// <summary>
    /// Releases SortedList1_MCParent from DC.Data.SortedList1_MCParents as part of a transaction rollback of Store().
    /// </summary>
    internal static void RollbackItemStore(IStorageItem item) {
      var sortedList1_MCParent = (SortedList1_MCParent) item;
      sortedList1_MCParent.onRollbackItemStored();
    }
    partial void onRollbackItemStored();


    /// <summary>
    /// Restores the SortedList1_MCParent item data as it was before the last update as part of a transaction rollback.
    /// </summary>
    internal static void RollbackItemUpdate(IStorageItem oldStorageItem, IStorageItem newStorageItem) {
      var oldItem = (SortedList1_MCParent) oldStorageItem;//an item clone with the values before item was updated
      var item = (SortedList1_MCParent) newStorageItem;//is the instance whose values should be restored

      // updated item: restore old values
      item.Name = oldItem.Name;
      item.onRollbackItemUpdated(oldItem);
    }
    partial void onRollbackItemUpdated(SortedList1_MCParent oldSortedList1_MCParent);


    /// <summary>
    /// Adds SortedList1_MCParent to DC.Data.SortedList1_MCParents as part of a transaction rollback of Release().
    /// </summary>
    internal static void RollbackItemRelease(IStorageItem item) {
      var sortedList1_MCParent = (SortedList1_MCParent) item;
      sortedList1_MCParent.onRollbackItemRelease();
    }
    partial void onRollbackItemRelease();


    /// <summary>
    /// Returns property values for tracing. Parents are shown with their key instead their content.
    /// </summary>
    public string ToTraceString() {
      var returnString =
        $"{this.GetKeyOrHash()}|" +
        $" {Name}";
      onToTraceString(ref returnString);
      return returnString;
    }
    partial void onToTraceString(ref string returnString);


    /// <summary>
    /// Returns property values
    /// </summary>
    public string ToShortString() {
      var returnString =
        $"{Key.ToKeyString()}," +
        $" {Name}";
      onToShortString(ref returnString);
      return returnString;
    }
    partial void onToShortString(ref string returnString);


    /// <summary>
    /// Returns all property names and values
    /// </summary>
    public override string ToString() {
      var returnString =
        $"Key: {Key.ToKeyString()}," +
        $" Name: {Name}," +
        $" Children: {Children.Count};";
      onToString(ref returnString);
      return returnString;
    }
    partial void onToString(ref string returnString);
    #endregion
  }
}
