//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by StorageClassGenerator
//
//     Do not change code in this file, it will get lost when the file gets 
//     auto generated again. Write your code into DictionaryParentN.cs.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;
using System.Threading;
using StorageLib;


namespace StorageDataContext  {


  public partial class DictionaryParentN: IStorageItemGeneric<DictionaryParentN> {

    #region Properties
    //      ----------

    /// <summary>
    /// Unique identifier for DictionaryParentN. Gets set once DictionaryParentN gets added to DC.Data.
    /// </summary>
    public int Key { get; private set; }
    internal static void SetKey(IStorageItem dictionaryParentN, int key, bool isRollback) {
#if DEBUG
      if (isRollback) {
        if (key==StorageExtensions.NoKey) {
          DC.Trace?.Invoke($"Release DictionaryParentN key @{dictionaryParentN.Key} #{dictionaryParentN.GetHashCode()}");
        } else {
          DC.Trace?.Invoke($"Store DictionaryParentN key @{key} #{dictionaryParentN.GetHashCode()}");
        }
      }
#endif
      ((DictionaryParentN)dictionaryParentN).Key = key;
    }


    public string Text { get; private set; }


    public IReadOnlyDictionary<string, DictionaryChild> DictionaryChidren => dictionaryChidren;
    readonly Dictionary<string, DictionaryChild> dictionaryChidren;


    /// <summary>
    /// Headers written to first line in CSV file
    /// </summary>
    internal static readonly string[] Headers = {"Key", "Text"};


    /// <summary>
    /// None existing DictionaryParentN
    /// </summary>
    internal static DictionaryParentN NoDictionaryParentN = new DictionaryParentN("NoText", isStoring: false);
    #endregion


    #region Events
    //      ------

    /// <summary>
    /// Content of DictionaryParentN has changed. Gets only raised for changes occurring after loading DC.Data with previously stored data.
    /// </summary>
    public event Action</*old*/DictionaryParentN, /*new*/DictionaryParentN>? HasChanged;
    #endregion


    #region Constructors
    //      ------------

    /// <summary>
    /// DictionaryParentN Constructor. If isStoring is true, adds DictionaryParentN to DC.Data.DictionaryParentNs.
    /// </summary>
    public DictionaryParentN(string text, bool isStoring = true) {
      Key = StorageExtensions.NoKey;
      Text = text;
      dictionaryChidren = new Dictionary<string, DictionaryChild>();
#if DEBUG
      DC.Trace?.Invoke($"new DictionaryParentN: {ToTraceString()}");
#endif
      onConstruct();
      if (DC.Data.IsTransaction) {
        DC.Data.AddTransaction(new TransactionItem(16,TransactionActivityEnum.New, Key, this));
      }

      if (isStoring) {
        Store();
      }
    }
    partial void onConstruct();


    /// <summary>
    /// Cloning constructor. It will copy all data from original except any collection (children).
    /// </summary>
    #pragma warning disable CS8618 // Children collections are uninitialized.
    public DictionaryParentN(DictionaryParentN original) {
    #pragma warning restore CS8618 //
      Key = StorageExtensions.NoKey;
      Text = original.Text;
      onCloned(this);
    }
    partial void onCloned(DictionaryParentN clone);


    /// <summary>
    /// Constructor for DictionaryParentN read from CSV file
    /// </summary>
    private DictionaryParentN(int key, CsvReader csvReader){
      Key = key;
      Text = csvReader.ReadString();
      dictionaryChidren = new Dictionary<string, DictionaryChild>();
      onCsvConstruct();
    }
    partial void onCsvConstruct();


    /// <summary>
    /// New DictionaryParentN read from CSV file
    /// </summary>
    internal static DictionaryParentN Create(int key, CsvReader csvReader) {
      return new DictionaryParentN(key, csvReader);
    }
    #endregion


    #region Methods
    //      -------

    /// <summary>
    /// Adds DictionaryParentN to DC.Data.DictionaryParentNs.<br/>
    /// Throws an Exception when DictionaryParentN is already stored.
    /// </summary>
    public void Store() {
      if (Key>=0) {
        throw new Exception($"DictionaryParentN cannot be stored again in DC.Data, key {Key} is greater equal 0." + Environment.NewLine + ToString());
      }

      var isCancelled = false;
      onStoring(ref isCancelled);
      if (isCancelled) return;

      DC.Data._DictionaryParentNs.Add(this);
      onStored();
#if DEBUG
      DC.Trace?.Invoke($"Stored DictionaryParentN #{GetHashCode()} @{Key}");
#endif
    }
    partial void onStoring(ref bool isCancelled);
    partial void onStored();


    /// <summary>
    /// Estimated number of UTF8 characters needed to write DictionaryParentN to CSV file
    /// </summary>
    public const int EstimatedLineLength = 150;


    /// <summary>
    /// Write DictionaryParentN to CSV file
    /// </summary>
    internal static void Write(DictionaryParentN dictionaryParentN, CsvWriter csvWriter) {
      dictionaryParentN.onCsvWrite();
      csvWriter.Write(dictionaryParentN.Text);
    }
    partial void onCsvWrite();


    /// <summary>
    /// Updates DictionaryParentN with the provided values
    /// </summary>
    public void Update(string text) {
      var clone = new DictionaryParentN(this);
      var isCancelled = false;
      onUpdating(text, ref isCancelled);
      if (isCancelled) return;

#if DEBUG
      DC.Trace?.Invoke($"Updating DictionaryParentN: {ToTraceString()}");
#endif

      //update properties and detect if any value has changed
      var isChangeDetected = false;
      if (Text!=text) {
        Text = text;
        isChangeDetected = true;
      }
      if (isChangeDetected) {
        onUpdated(clone);
        if (Key>=0) {
          DC.Data._DictionaryParentNs.ItemHasChanged(clone, this);
        } else if (DC.Data.IsTransaction) {
          DC.Data.AddTransaction(new TransactionItem(16, TransactionActivityEnum.Update, Key, this, oldItem: clone));
        }
        HasChanged?.Invoke(clone, this);
      }
#if DEBUG
      DC.Trace?.Invoke($"Updated DictionaryParentN: {ToTraceString()}");
#endif
    }
    partial void onUpdating(string text, ref bool isCancelled);
    partial void onUpdated(DictionaryParentN old);


    /// <summary>
    /// Updates this DictionaryParentN with values from CSV file
    /// </summary>
    internal static void Update(DictionaryParentN dictionaryParentN, CsvReader csvReader){
      dictionaryParentN.Text = csvReader.ReadString();
      dictionaryParentN.onCsvUpdate();
    }
    partial void onCsvUpdate();


    /// <summary>
    /// Add dictionaryChild to DictionaryChidren.
    /// </summary>
    internal void AddToDictionaryChidren(DictionaryChild dictionaryChild) {
#if DEBUG
      if (dictionaryChild==DictionaryChild.NoDictionaryChild) throw new Exception();
      if ((dictionaryChild.Key>=0)&&(Key<0)) throw new Exception();
      if (dictionaryChidren.ContainsKey(dictionaryChild.Text)) throw new Exception();
#endif
      dictionaryChidren.Add(dictionaryChild.Text, dictionaryChild);
      onAddedToDictionaryChidren(dictionaryChild);
#if DEBUG
      DC.Trace?.Invoke($"Add DictionaryChild {dictionaryChild.GetKeyOrHash()} to " +
        $"{this.GetKeyOrHash()} DictionaryParentN.DictionaryChidren");
#endif
    }
    partial void onAddedToDictionaryChidren(DictionaryChild dictionaryChild);


    /// <summary>
    /// Removes dictionaryChild from DictionaryParentN.
    /// </summary>
    internal void RemoveFromDictionaryChidren(DictionaryChild dictionaryChild) {
#if DEBUG
      if (!dictionaryChidren.Remove(dictionaryChild.Text)) throw new Exception();
#else
        dictionaryChidren.Remove(dictionaryChild.Text);
#endif
      onRemovedFromDictionaryChidren(dictionaryChild);
#if DEBUG
      DC.Trace?.Invoke($"Remove DictionaryChild {dictionaryChild.GetKeyOrHash()} from " +
        $"{this.GetKeyOrHash()} DictionaryParentN.DictionaryChidren");
#endif
    }
    partial void onRemovedFromDictionaryChidren(DictionaryChild dictionaryChild);


    /// <summary>
    /// Removes DictionaryParentN from DC.Data.DictionaryParentNs.
    /// </summary>
    public void Release() {
      if (Key<0) {
        throw new Exception($"DictionaryParentN.Release(): DictionaryParentN '{this}' is not stored in DC.Data, key is {Key}.");
      }
      foreach (var dictionaryChild in DictionaryChidren.Values) {
        if (dictionaryChild?.Key>=0) {
          throw new Exception($"Cannot release DictionaryParentN '{this}' " + Environment.NewLine + 
            $"because '{dictionaryChild}' in DictionaryParentN.DictionaryChidren is still stored.");
        }
      }
      onReleased();
      DC.Data._DictionaryParentNs.Remove(Key);
#if DEBUG
      DC.Trace?.Invoke($"Released DictionaryParentN @{Key} #{GetHashCode()}");
#endif
    }
    partial void onReleased();


    /// <summary>
    /// Undoes the new() statement as part of a transaction rollback.
    /// </summary>
    internal static void RollbackItemNew(IStorageItem item) {
      var dictionaryParentN = (DictionaryParentN) item;
#if DEBUG
      DC.Trace?.Invoke($"Rollback new DictionaryParentN(): {dictionaryParentN.ToTraceString()}");
#endif
      dictionaryParentN.onRollbackItemNew();
    }
    partial void onRollbackItemNew();


    /// <summary>
    /// Releases DictionaryParentN from DC.Data.DictionaryParentNs as part of a transaction rollback of Store().
    /// </summary>
    internal static void RollbackItemStore(IStorageItem item) {
      var dictionaryParentN = (DictionaryParentN) item;
#if DEBUG
      DC.Trace?.Invoke($"Rollback DictionaryParentN.Store(): {dictionaryParentN.ToTraceString()}");
#endif
      dictionaryParentN.onRollbackItemStored();
    }
    partial void onRollbackItemStored();


    /// <summary>
    /// Restores the DictionaryParentN item data as it was before the last update as part of a transaction rollback.
    /// </summary>
    internal static void RollbackItemUpdate(IStorageItem oldStorageItem, IStorageItem newStorageItem) {
      var oldItem = (DictionaryParentN) oldStorageItem;//an item clone with the values before item was updated
      var item = (DictionaryParentN) newStorageItem;//is the instance whose values should be restored
#if DEBUG
      DC.Trace?.Invoke($"Rolling back DictionaryParentN.Update(): {item.ToTraceString()}");
#endif

      // updated item: restore old values
      item.Text = oldItem.Text;
      item.onRollbackItemUpdated(oldItem);
#if DEBUG
      DC.Trace?.Invoke($"Rolled back DictionaryParentN.Update(): {item.ToTraceString()}");
#endif
    }
    partial void onRollbackItemUpdated(DictionaryParentN oldDictionaryParentN);


    /// <summary>
    /// Adds DictionaryParentN to DC.Data.DictionaryParentNs as part of a transaction rollback of Release().
    /// </summary>
    internal static void RollbackItemRelease(IStorageItem item) {
      var dictionaryParentN = (DictionaryParentN) item;
#if DEBUG
      DC.Trace?.Invoke($"Rollback DictionaryParentN.Release(): {dictionaryParentN.ToTraceString()}");
#endif
      dictionaryParentN.onRollbackItemRelease();
    }
    partial void onRollbackItemRelease();


    /// <summary>
    /// Returns property values for tracing. Parents are shown with their key instead their content.
    /// </summary>
    public string ToTraceString() {
      var returnString =
        $"{this.GetKeyOrHash()}|" +
        $" {Text}";
      onToTraceString(ref returnString);
      return returnString;
    }
    partial void onToTraceString(ref string returnString);


    /// <summary>
    /// Returns property values
    /// </summary>
    public string ToShortString() {
      var returnString =
        $"{Key.ToKeyString()}," +
        $" {Text}";
      onToShortString(ref returnString);
      return returnString;
    }
    partial void onToShortString(ref string returnString);


    /// <summary>
    /// Returns all property names and values
    /// </summary>
    public override string ToString() {
      var returnString =
        $"Key: {Key.ToKeyString()}," +
        $" Text: {Text}," +
        $" DictionaryChidren: {DictionaryChidren.Count};";
      onToString(ref returnString);
      return returnString;
    }
    partial void onToString(ref string returnString);
    #endregion
  }
}
