//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by StorageClassGenerator
//
//     Do not change code in this file, it will get lost when the file gets 
//     auto generated again. Write your code into ListParentN.cs.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;
using System.Threading;
using StorageLib;


namespace TestContext  {


  public partial class ListParentN: IStorageItemGeneric<ListParentN> {

    #region Properties
    //      ----------

    /// <summary>
    /// Unique identifier for ListParentN. Gets set once ListParentN gets added to DC.Data.
    /// </summary>
    public int Key { get; private set; }
    internal static void SetKey(IStorageItem listParentN, int key, bool isRollback) {
#if DEBUG
      if (isRollback) {
        if (key==StorageExtensions.NoKey) {
          DC.Trace?.Invoke($"Release ListParentN key @{listParentN.Key} #{listParentN.GetHashCode()}");
        } else {
          DC.Trace?.Invoke($"Store ListParentN key @{key} #{listParentN.GetHashCode()}");
        }
      }
#endif
      ((ListParentN)listParentN).Key = key;
    }


    public string Text { get; private set; }


    public IReadOnlyList<ListChild> Children => children;
    readonly List<ListChild> children;


    /// <summary>
    /// Headers written to first line in CSV file
    /// </summary>
    internal static readonly string[] Headers = {"Key", "Text"};


    /// <summary>
    /// None existing ListParentN, used as a temporary place holder when reading a CSV file
    /// which was not compacted. It might create first a later deleted item linking to a 
    /// deleted parent. In this case, the parent property gets set to NoListParentN. Once the CSV
    /// file is completely read, that child will actually be deleted (released) and Verify()
    /// ensures that there are no stored children with links to NoListParentN.
    /// </summary>
    internal static ListParentN NoListParentN = new ListParentN("NoText", isStoring: false);
    #endregion


    #region Events
    //      ------

    /// <summary>
    /// Content of ListParentN has changed. Gets only raised for changes occurring after loading DC.Data with previously stored data.
    /// </summary>
    public event Action</*old*/ListParentN, /*new*/ListParentN>? HasChanged;
    #endregion


    #region Constructors
    //      ------------

    /// <summary>
    /// ListParentN Constructor. If isStoring is true, adds ListParentN to DC.Data.ListParentNs.
    /// </summary>
    public ListParentN(string text, bool isStoring = true) {
      Key = StorageExtensions.NoKey;
      Text = text;
      children = new List<ListChild>();
#if DEBUG
      DC.Trace?.Invoke($"new ListParentN: {ToTraceString()}");
#endif
      onConstruct();
      if (DC.Data.IsTransaction) {
        DC.Data.AddTransaction(new TransactionItem(11,TransactionActivityEnum.New, Key, this));
      }

      if (isStoring) {
        Store();
      }
    }
    partial void onConstruct();


    /// <summary>
    /// Cloning constructor. It will copy all data from original except any collection (children).
    /// </summary>
    #pragma warning disable CS8618 // Children collections are uninitialized.
    public ListParentN(ListParentN original) {
    #pragma warning restore CS8618 //
      Key = StorageExtensions.NoKey;
      Text = original.Text;
      onCloned(this);
    }
    partial void onCloned(ListParentN clone);


    /// <summary>
    /// Constructor for ListParentN read from CSV file
    /// </summary>
    private ListParentN(int key, CsvReader csvReader){
      Key = key;
      Text = csvReader.ReadString();
      children = new List<ListChild>();
      onCsvConstruct();
    }
    partial void onCsvConstruct();


    /// <summary>
    /// New ListParentN read from CSV file
    /// </summary>
    internal static ListParentN Create(int key, CsvReader csvReader) {
      return new ListParentN(key, csvReader);
    }
    #endregion


    #region Methods
    //      -------

    /// <summary>
    /// Adds ListParentN to DC.Data.ListParentNs.<br/>
    /// Throws an Exception when ListParentN is already stored.
    /// </summary>
    public void Store() {
      if (Key>=0) {
        throw new Exception($"ListParentN cannot be stored again in DC.Data, key {Key} is greater equal 0." + Environment.NewLine + ToString());
      }

      var isCancelled = false;
      onStoring(ref isCancelled);
      if (isCancelled) return;

      DC.Data._ListParentNs.Add(this);
      onStored();
#if DEBUG
      DC.Trace?.Invoke($"Stored ListParentN #{GetHashCode()} @{Key}");
#endif
    }
    partial void onStoring(ref bool isCancelled);
    partial void onStored();


    /// <summary>
    /// Estimated number of UTF8 characters needed to write ListParentN to CSV file
    /// </summary>
    public const int EstimatedLineLength = 150;


    /// <summary>
    /// Write ListParentN to CSV file
    /// </summary>
    internal static void Write(ListParentN listParentN, CsvWriter csvWriter) {
      listParentN.onCsvWrite();
      csvWriter.Write(listParentN.Text);
    }
    partial void onCsvWrite();


    /// <summary>
    /// Updates ListParentN with the provided values
    /// </summary>
    public void Update(string text) {
      var clone = new ListParentN(this);
      var isCancelled = false;
      onUpdating(text, ref isCancelled);
      if (isCancelled) return;

#if DEBUG
      DC.Trace?.Invoke($"Updating ListParentN: {ToTraceString()}");
#endif

      //update properties and detect if any value has changed
      var isChangeDetected = false;
      if (Text!=text) {
        Text = text;
        isChangeDetected = true;
      }
      if (isChangeDetected) {
        onUpdated(clone);
        if (Key>=0) {
          DC.Data._ListParentNs.ItemHasChanged(clone, this);
        } else if (DC.Data.IsTransaction) {
          DC.Data.AddTransaction(new TransactionItem(11, TransactionActivityEnum.Update, Key, this, oldItem: clone));
        }
        HasChanged?.Invoke(clone, this);
      }
#if DEBUG
      DC.Trace?.Invoke($"Updated ListParentN: {ToTraceString()}");
#endif
    }
    partial void onUpdating(string text, ref bool isCancelled);
    partial void onUpdated(ListParentN old);


    /// <summary>
    /// Updates this ListParentN with values from CSV file
    /// </summary>
    internal static void Update(ListParentN listParentN, CsvReader csvReader){
      listParentN.Text = csvReader.ReadString();
      listParentN.onCsvUpdate();
    }
    partial void onCsvUpdate();


    /// <summary>
    /// Add listChild to Children.
    /// </summary>
    internal void AddToChildren(ListChild listChild) {
#if DEBUG
      if (listChild==ListChild.NoListChild) throw new Exception();
      if ((listChild.Key>=0)&&(Key<0)) throw new Exception();
      if (children.Contains(listChild)) throw new Exception();
#endif
      children.Add(listChild);
      onAddedToChildren(listChild);
#if DEBUG
      DC.Trace?.Invoke($"Add ListChild {listChild.GetKeyOrHash()} to " +
        $"{this.GetKeyOrHash()} ListParentN.Children");
#endif
    }
    partial void onAddedToChildren(ListChild listChild);


    /// <summary>
    /// Removes listChild from ListParentN.
    /// </summary>
    internal void RemoveFromChildren(ListChild listChild) {
#if DEBUG
      if (!children.Remove(listChild)) throw new Exception();
#else
        children.Remove(listChild);
#endif
      onRemovedFromChildren(listChild);
#if DEBUG
      DC.Trace?.Invoke($"Remove ListChild {listChild.GetKeyOrHash()} from " +
        $"{this.GetKeyOrHash()} ListParentN.Children");
#endif
    }
    partial void onRemovedFromChildren(ListChild listChild);


    /// <summary>
    /// Removes ListParentN from DC.Data.ListParentNs.
    /// </summary>
    public void Release() {
      if (Key<0) {
        throw new Exception($"ListParentN.Release(): ListParentN '{this}' is not stored in DC.Data, key is {Key}.");
      }
      foreach (var listChild in Children) {
        if (listChild?.Key>=0) {
          throw new Exception($"Cannot release ListParentN '{this}' " + Environment.NewLine + 
            $"because '{listChild}' in ListParentN.Children is still stored.");
        }
      }
      onReleased();
      DC.Data._ListParentNs.Remove(Key);
#if DEBUG
      DC.Trace?.Invoke($"Released ListParentN @{Key} #{GetHashCode()}");
#endif
    }
    partial void onReleased();


    /// <summary>
    /// Undoes the new() statement as part of a transaction rollback.
    /// </summary>
    internal static void RollbackItemNew(IStorageItem item) {
      var listParentN = (ListParentN) item;
#if DEBUG
      DC.Trace?.Invoke($"Rollback new ListParentN(): {listParentN.ToTraceString()}");
#endif
      listParentN.onRollbackItemNew();
    }
    partial void onRollbackItemNew();


    /// <summary>
    /// Releases ListParentN from DC.Data.ListParentNs as part of a transaction rollback of Store().
    /// </summary>
    internal static void RollbackItemStore(IStorageItem item) {
      var listParentN = (ListParentN) item;
#if DEBUG
      DC.Trace?.Invoke($"Rollback ListParentN.Store(): {listParentN.ToTraceString()}");
#endif
      listParentN.onRollbackItemStored();
    }
    partial void onRollbackItemStored();


    /// <summary>
    /// Restores the ListParentN item data as it was before the last update as part of a transaction rollback.
    /// </summary>
    internal static void RollbackItemUpdate(IStorageItem oldStorageItem, IStorageItem newStorageItem) {
      var oldItem = (ListParentN) oldStorageItem;//an item clone with the values before item was updated
      var item = (ListParentN) newStorageItem;//is the instance whose values should be restored
#if DEBUG
      DC.Trace?.Invoke($"Rolling back ListParentN.Update(): {item.ToTraceString()}");
#endif

      // updated item: restore old values
      item.Text = oldItem.Text;
      item.onRollbackItemUpdated(oldItem);
#if DEBUG
      DC.Trace?.Invoke($"Rolled back ListParentN.Update(): {item.ToTraceString()}");
#endif
    }
    partial void onRollbackItemUpdated(ListParentN oldListParentN);


    /// <summary>
    /// Adds ListParentN to DC.Data.ListParentNs as part of a transaction rollback of Release().
    /// </summary>
    internal static void RollbackItemRelease(IStorageItem item) {
      var listParentN = (ListParentN) item;
#if DEBUG
      DC.Trace?.Invoke($"Rollback ListParentN.Release(): {listParentN.ToTraceString()}");
#endif
      listParentN.onRollbackItemRelease();
    }
    partial void onRollbackItemRelease();


    /// <summary>
    /// Returns property values for tracing. Parents are shown with their key instead their content.
    /// </summary>
    public string ToTraceString() {
      var returnString =
        $"{this.GetKeyOrHash()}|" +
        $" {Text}";
      onToTraceString(ref returnString);
      return returnString;
    }
    partial void onToTraceString(ref string returnString);


    /// <summary>
    /// Returns property values
    /// </summary>
    public string ToShortString() {
      var returnString =
        $"{Key.ToKeyString()}," +
        $" {Text}";
      onToShortString(ref returnString);
      return returnString;
    }
    partial void onToShortString(ref string returnString);


    /// <summary>
    /// Returns all property names and values
    /// </summary>
    public override string ToString() {
      var returnString =
        $"Key: {Key.ToKeyString()}," +
        $" Text: {Text}," +
        $" Children: {Children.Count};";
      onToString(ref returnString);
      return returnString;
    }
    partial void onToString(ref string returnString);
    #endregion
  }
}
