//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by StorageClassGenerator
//
//     Do not change code in this file, it will get lost when the file gets 
//     auto generated again. Write your code into NotMatchingChildrenListName_Child.cs.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;
using System.Threading;
using StorageLib;


namespace TestContext  {


    /// <summary>
    /// Child for NotMatchingChildrenListName_Parent
    /// </summary>
  public partial class NotMatchingChildrenListName_Child: IStorageItemGeneric<NotMatchingChildrenListName_Child> {

    #region Properties
    //      ----------

    /// <summary>
    /// Unique identifier for NotMatchingChildrenListName_Child. Gets set once NotMatchingChildrenListName_Child gets added to DC.Data.
    /// </summary>
    public int Key { get; private set; }
    internal static void SetKey(IStorageItem notMatchingChildrenListName_Child, int key, bool isRollback) {
#if DEBUG
      if (isRollback) {
        if (key==StorageExtensions.NoKey) {
          DC.Trace?.Invoke($"Release NotMatchingChildrenListName_Child key @{notMatchingChildrenListName_Child.Key} #{notMatchingChildrenListName_Child.GetHashCode()}");
        } else {
          DC.Trace?.Invoke($"Store NotMatchingChildrenListName_Child key @{key} #{notMatchingChildrenListName_Child.GetHashCode()}");
        }
      }
#endif
      ((NotMatchingChildrenListName_Child)notMatchingChildrenListName_Child).Key = key;
    }


    /// <summary>
    /// Some Text
    /// </summary>
    public string Text { get; private set; }


    /// <summary>
    /// Deletable children which must have a parent
    /// </summary>
    public NotMatchingChildrenListName_Parent Parent { get; private set; }


    /// <summary>
    /// Headers written to first line in CSV file
    /// </summary>
    internal static readonly string[] Headers = {"Key", "Text", "Parent"};


    /// <summary>
    /// None existing NotMatchingChildrenListName_Child
    /// </summary>
    internal static NotMatchingChildrenListName_Child NoNotMatchingChildrenListName_Child = new NotMatchingChildrenListName_Child("NoText", NotMatchingChildrenListName_Parent.NoNotMatchingChildrenListName_Parent, isStoring: false);
    #endregion


    #region Events
    //      ------

    /// <summary>
    /// Content of NotMatchingChildrenListName_Child has changed. Gets only raised for changes occurring after loading DC.Data with previously stored data.
    /// </summary>
    public event Action</*old*/NotMatchingChildrenListName_Child, /*new*/NotMatchingChildrenListName_Child>? HasChanged;
    #endregion


    #region Constructors
    //      ------------

    /// <summary>
    /// NotMatchingChildrenListName_Child Constructor. If isStoring is true, adds NotMatchingChildrenListName_Child to DC.Data.NotMatchingChildrenListName_Childs.
    /// </summary>
    public NotMatchingChildrenListName_Child(string text, NotMatchingChildrenListName_Parent parent, bool isStoring = true) {
      Key = StorageExtensions.NoKey;
      Text = text;
      Parent = parent;
#if DEBUG
      DC.Trace?.Invoke($"new NotMatchingChildrenListName_Child: {ToTraceString()}");
#endif
      Parent.AddToChildren(this);
      onConstruct();
      if (DC.Data.IsTransaction) {
        DC.Data.AddTransaction(new TransactionItem(32,TransactionActivityEnum.New, Key, this));
      }

      if (isStoring) {
        Store();
      }
    }
    partial void onConstruct();


    /// <summary>
    /// Cloning constructor. It will copy all data from original except any collection (children).
    /// </summary>
    #pragma warning disable CS8618 // Children collections are uninitialized.
    public NotMatchingChildrenListName_Child(NotMatchingChildrenListName_Child original) {
    #pragma warning restore CS8618 //
      Key = StorageExtensions.NoKey;
      Text = original.Text;
      Parent = original.Parent;
      onCloned(this);
    }
    partial void onCloned(NotMatchingChildrenListName_Child clone);


    /// <summary>
    /// Constructor for NotMatchingChildrenListName_Child read from CSV file
    /// </summary>
    private NotMatchingChildrenListName_Child(int key, CsvReader csvReader){
      Key = key;
      Text = csvReader.ReadString();
      var notMatchingChildrenListName_ParentKey = csvReader.ReadInt();
      Parent = DC.Data._NotMatchingChildrenListName_Parents.GetItem(notMatchingChildrenListName_ParentKey)??
        throw new Exception($"Read NotMatchingChildrenListName_Child from CSV file: Cannot find Parent with key {notMatchingChildrenListName_ParentKey}." + Environment.NewLine + 
          csvReader.PresentContent);
      if (Parent!=NotMatchingChildrenListName_Parent.NoNotMatchingChildrenListName_Parent) {
        Parent.AddToChildren(this);
      }
      onCsvConstruct();
    }
    partial void onCsvConstruct();


    /// <summary>
    /// New NotMatchingChildrenListName_Child read from CSV file
    /// </summary>
    internal static NotMatchingChildrenListName_Child Create(int key, CsvReader csvReader) {
      return new NotMatchingChildrenListName_Child(key, csvReader);
    }


    /// <summary>
    /// Verify that notMatchingChildrenListName_Child.Parent exists.
    /// </summary>
    internal static bool Verify(NotMatchingChildrenListName_Child notMatchingChildrenListName_Child) {
      if (notMatchingChildrenListName_Child.Parent==NotMatchingChildrenListName_Parent.NoNotMatchingChildrenListName_Parent) return false;
      return true;
    }
    #endregion


    #region Methods
    //      -------

    /// <summary>
    /// Adds NotMatchingChildrenListName_Child to DC.Data.NotMatchingChildrenListName_Childs.<br/>
    /// Throws an Exception when NotMatchingChildrenListName_Child is already stored.
    /// </summary>
    public void Store() {
      if (Key>=0) {
        throw new Exception($"NotMatchingChildrenListName_Child cannot be stored again in DC.Data, key {Key} is greater equal 0." + Environment.NewLine + ToString());
      }

      var isCancelled = false;
      onStoring(ref isCancelled);
      if (isCancelled) return;

      if (Parent.Key<0) {
        throw new Exception($"Cannot store child NotMatchingChildrenListName_Child '{this}'.Parent to NotMatchingChildrenListName_Parent '{Parent}' because parent is not stored yet.");
      }
      DC.Data._NotMatchingChildrenListName_Childs.Add(this);
      onStored();
#if DEBUG
      DC.Trace?.Invoke($"Stored NotMatchingChildrenListName_Child #{GetHashCode()} @{Key}");
#endif
    }
    partial void onStoring(ref bool isCancelled);
    partial void onStored();


    /// <summary>
    /// Estimated number of UTF8 characters needed to write NotMatchingChildrenListName_Child to CSV file
    /// </summary>
    public const int EstimatedLineLength = 150;


    /// <summary>
    /// Write NotMatchingChildrenListName_Child to CSV file
    /// </summary>
    internal static void Write(NotMatchingChildrenListName_Child notMatchingChildrenListName_Child, CsvWriter csvWriter) {
      notMatchingChildrenListName_Child.onCsvWrite();
      csvWriter.Write(notMatchingChildrenListName_Child.Text);
      if (notMatchingChildrenListName_Child.Parent.Key<0) throw new Exception($"Cannot write notMatchingChildrenListName_Child '{notMatchingChildrenListName_Child}' to CSV File, because Parent is not stored in DC.Data.NotMatchingChildrenListName_Parents.");

      csvWriter.Write(notMatchingChildrenListName_Child.Parent.Key.ToString());
    }
    partial void onCsvWrite();


    /// <summary>
    /// Updates NotMatchingChildrenListName_Child with the provided values
    /// </summary>
    public void Update(string text, NotMatchingChildrenListName_Parent parent) {
      if (Key>=0){
        if (parent.Key<0) {
          throw new Exception($"NotMatchingChildrenListName_Child.Update(): It is illegal to add stored NotMatchingChildrenListName_Child '{this}'" + Environment.NewLine + 
            $"to Parent '{parent}', which is not stored.");
        }
      }
      var clone = new NotMatchingChildrenListName_Child(this);
      var isCancelled = false;
      onUpdating(text, parent, ref isCancelled);
      if (isCancelled) return;

#if DEBUG
      DC.Trace?.Invoke($"Updating NotMatchingChildrenListName_Child: {ToTraceString()}");
#endif

      //remove not yet updated item from parents which will be removed by update
      var hasParentChanged = Parent!=parent;
      if (hasParentChanged) {
        Parent.RemoveFromChildren(this);
      }

      //update properties and detect if any value has changed
      var isChangeDetected = false;
      if (Text!=text) {
        Text = text;
        isChangeDetected = true;
      }
      if (Parent!=parent) {
        Parent = parent;
        isChangeDetected = true;
      }

      //add updated item to parents which have been newly added during update
      if (hasParentChanged) {
        Parent.AddToChildren(this);
      }
      if (isChangeDetected) {
        onUpdated(clone);
        if (Key>=0) {
          DC.Data._NotMatchingChildrenListName_Childs.ItemHasChanged(clone, this);
        } else if (DC.Data.IsTransaction) {
          DC.Data.AddTransaction(new TransactionItem(32, TransactionActivityEnum.Update, Key, this, oldItem: clone));
        }
        HasChanged?.Invoke(clone, this);
      }
#if DEBUG
      DC.Trace?.Invoke($"Updated NotMatchingChildrenListName_Child: {ToTraceString()}");
#endif
    }
    partial void onUpdating(string text, NotMatchingChildrenListName_Parent parent, ref bool isCancelled);
    partial void onUpdated(NotMatchingChildrenListName_Child old);


    /// <summary>
    /// Updates this NotMatchingChildrenListName_Child with values from CSV file
    /// </summary>
    internal static void Update(NotMatchingChildrenListName_Child notMatchingChildrenListName_Child, CsvReader csvReader){
      notMatchingChildrenListName_Child.Text = csvReader.ReadString();
        var parent = DC.Data._NotMatchingChildrenListName_Parents.GetItem(csvReader.ReadInt())??
          NotMatchingChildrenListName_Parent.NoNotMatchingChildrenListName_Parent;
      if (notMatchingChildrenListName_Child.Parent!=parent) {
        if (notMatchingChildrenListName_Child.Parent!=NotMatchingChildrenListName_Parent.NoNotMatchingChildrenListName_Parent) {
          notMatchingChildrenListName_Child.Parent.RemoveFromChildren(notMatchingChildrenListName_Child);
        }
        notMatchingChildrenListName_Child.Parent = parent;
        notMatchingChildrenListName_Child.Parent.AddToChildren(notMatchingChildrenListName_Child);
      }
      notMatchingChildrenListName_Child.onCsvUpdate();
    }
    partial void onCsvUpdate();


    /// <summary>
    /// Removes NotMatchingChildrenListName_Child from DC.Data.NotMatchingChildrenListName_Childs.
    /// </summary>
    public void Release() {
      if (Key<0) {
        throw new Exception($"NotMatchingChildrenListName_Child.Release(): NotMatchingChildrenListName_Child '{this}' is not stored in DC.Data, key is {Key}.");
      }
      onReleased();
      DC.Data._NotMatchingChildrenListName_Childs.Remove(Key);
#if DEBUG
      DC.Trace?.Invoke($"Released NotMatchingChildrenListName_Child @{Key} #{GetHashCode()}");
#endif
    }
    partial void onReleased();


    /// <summary>
    /// Removes NotMatchingChildrenListName_Child from parents as part of a transaction rollback of the new() statement.
    /// </summary>
    internal static void RollbackItemNew(IStorageItem item) {
      var notMatchingChildrenListName_Child = (NotMatchingChildrenListName_Child) item;
#if DEBUG
      DC.Trace?.Invoke($"Rollback new NotMatchingChildrenListName_Child(): {notMatchingChildrenListName_Child.ToTraceString()}");
#endif
      if (notMatchingChildrenListName_Child.Parent!=NotMatchingChildrenListName_Parent.NoNotMatchingChildrenListName_Parent) {
        notMatchingChildrenListName_Child.Parent.RemoveFromChildren(notMatchingChildrenListName_Child);
      }
      notMatchingChildrenListName_Child.onRollbackItemNew();
    }
    partial void onRollbackItemNew();


    /// <summary>
    /// Releases NotMatchingChildrenListName_Child from DC.Data.NotMatchingChildrenListName_Childs as part of a transaction rollback of Store().
    /// </summary>
    internal static void RollbackItemStore(IStorageItem item) {
      var notMatchingChildrenListName_Child = (NotMatchingChildrenListName_Child) item;
#if DEBUG
      DC.Trace?.Invoke($"Rollback NotMatchingChildrenListName_Child.Store(): {notMatchingChildrenListName_Child.ToTraceString()}");
#endif
      notMatchingChildrenListName_Child.onRollbackItemStored();
    }
    partial void onRollbackItemStored();


    /// <summary>
    /// Restores the NotMatchingChildrenListName_Child item data as it was before the last update as part of a transaction rollback.
    /// </summary>
    internal static void RollbackItemUpdate(IStorageItem oldStorageItem, IStorageItem newStorageItem) {
      var oldItem = (NotMatchingChildrenListName_Child) oldStorageItem;//an item clone with the values before item was updated
      var item = (NotMatchingChildrenListName_Child) newStorageItem;//is the instance whose values should be restored
#if DEBUG
      DC.Trace?.Invoke($"Rolling back NotMatchingChildrenListName_Child.Update(): {item.ToTraceString()}");
#endif

      // remove updated item from parents
      var hasParentChanged = oldItem.Parent!=item.Parent;
      if (hasParentChanged) {
        item.Parent.RemoveFromChildren(item);
      }

      // updated item: restore old values
      item.Text = oldItem.Text;
      item.Parent = oldItem.Parent;

      // add item with previous values to parents
      if (hasParentChanged) {
        item.Parent.AddToChildren(item);
      }
      item.onRollbackItemUpdated(oldItem);
#if DEBUG
      DC.Trace?.Invoke($"Rolled back NotMatchingChildrenListName_Child.Update(): {item.ToTraceString()}");
#endif
    }
    partial void onRollbackItemUpdated(NotMatchingChildrenListName_Child oldNotMatchingChildrenListName_Child);


    /// <summary>
    /// Adds NotMatchingChildrenListName_Child to DC.Data.NotMatchingChildrenListName_Childs as part of a transaction rollback of Release().
    /// </summary>
    internal static void RollbackItemRelease(IStorageItem item) {
      var notMatchingChildrenListName_Child = (NotMatchingChildrenListName_Child) item;
#if DEBUG
      DC.Trace?.Invoke($"Rollback NotMatchingChildrenListName_Child.Release(): {notMatchingChildrenListName_Child.ToTraceString()}");
#endif
      notMatchingChildrenListName_Child.onRollbackItemRelease();
    }
    partial void onRollbackItemRelease();


    /// <summary>
    /// Returns property values for tracing. Parents are shown with their key instead their content.
    /// </summary>
    public string ToTraceString() {
      var returnString =
        $"{this.GetKeyOrHash()}|" +
        $" {Text}|" +
        $" Parent {Parent.GetKeyOrHash()}";
      onToTraceString(ref returnString);
      return returnString;
    }
    partial void onToTraceString(ref string returnString);


    /// <summary>
    /// Returns property values
    /// </summary>
    public string ToShortString() {
      var returnString =
        $"{Key.ToKeyString()}," +
        $" {Text}," +
        $" {Parent.ToShortString()}";
      onToShortString(ref returnString);
      return returnString;
    }
    partial void onToShortString(ref string returnString);


    /// <summary>
    /// Returns all property names and values
    /// </summary>
    public override string ToString() {
      var returnString =
        $"Key: {Key.ToKeyString()}," +
        $" Text: {Text}," +
        $" Parent: {Parent.ToShortString()};";
      onToString(ref returnString);
      return returnString;
    }
    partial void onToString(ref string returnString);
    #endregion
  }
}
