//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by StorageClassGenerator
//
//     Do not change code in this file, it will get lost when the file gets 
//     auto generated again. Write your code into SingleChildParentNR.cs.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;
using System.Threading;
using StorageLib;


namespace StorageDataContext  {


  public partial class SingleChildParentNR: IStorageItemGeneric<SingleChildParentNR> {

    #region Properties
    //      ----------

    /// <summary>
    /// Unique identifier for SingleChildParentNR. Gets set once SingleChildParentNR gets added to DC.Data.
    /// </summary>
    public int Key { get; private set; }
    internal static void SetKey(IStorageItem singleChildParentNR, int key, bool isRollback) {
#if DEBUG
      if (isRollback) {
        if (key==StorageExtensions.NoKey) {
          DC.Trace?.Invoke($"Release SingleChildParentNR key @{singleChildParentNR.Key} #{singleChildParentNR.GetHashCode()}");
        } else {
          DC.Trace?.Invoke($"Store SingleChildParentNR key @{key} #{singleChildParentNR.GetHashCode()}");
        }
      }
#endif
      ((SingleChildParentNR)singleChildParentNR).Key = key;
    }


    public string Text { get; private set; }


    public SingleChildChild? Child { get; private set; }


    /// <summary>
    /// Headers written to first line in CSV file
    /// </summary>
    internal static readonly string[] Headers = {"Key", "Text"};


    /// <summary>
    /// None existing SingleChildParentNR
    /// </summary>
    internal static SingleChildParentNR NoSingleChildParentNR = new SingleChildParentNR("NoText", isStoring: false);
    #endregion


    #region Events
    //      ------

    /// <summary>
    /// Content of SingleChildParentNR has changed. Gets only raised for changes occurring after loading DC.Data with previously stored data.
    /// </summary>
    public event Action</*old*/SingleChildParentNR, /*new*/SingleChildParentNR>? HasChanged;
    #endregion


    #region Constructors
    //      ------------

    /// <summary>
    /// SingleChildParentNR Constructor. If isStoring is true, adds SingleChildParentNR to DC.Data.SingleChildParentNRs.
    /// </summary>
    public SingleChildParentNR(string text, bool isStoring = true) {
      Key = StorageExtensions.NoKey;
      Text = text;
#if DEBUG
      DC.Trace?.Invoke($"new SingleChildParentNR: {ToTraceString()}");
#endif
      onConstruct();
      if (DC.Data.IsTransaction) {
        DC.Data.AddTransaction(new TransactionItem(8,TransactionActivityEnum.New, Key, this));
      }

      if (isStoring) {
        Store();
      }
    }
    partial void onConstruct();


    /// <summary>
    /// Cloning constructor. It will copy all data from original except any collection (children).
    /// </summary>
    #pragma warning disable CS8618 // Children collections are uninitialized.
    public SingleChildParentNR(SingleChildParentNR original) {
    #pragma warning restore CS8618 //
      Key = StorageExtensions.NoKey;
      Text = original.Text;
      onCloned(this);
    }
    partial void onCloned(SingleChildParentNR clone);


    /// <summary>
    /// Constructor for SingleChildParentNR read from CSV file
    /// </summary>
    private SingleChildParentNR(int key, CsvReader csvReader){
      Key = key;
      Text = csvReader.ReadString();
      onCsvConstruct();
    }
    partial void onCsvConstruct();


    /// <summary>
    /// New SingleChildParentNR read from CSV file
    /// </summary>
    internal static SingleChildParentNR Create(int key, CsvReader csvReader) {
      return new SingleChildParentNR(key, csvReader);
    }
    #endregion


    #region Methods
    //      -------

    /// <summary>
    /// Adds SingleChildParentNR to DC.Data.SingleChildParentNRs.<br/>
    /// Throws an Exception when SingleChildParentNR is already stored.
    /// </summary>
    public void Store() {
      if (Key>=0) {
        throw new Exception($"SingleChildParentNR cannot be stored again in DC.Data, key {Key} is greater equal 0." + Environment.NewLine + ToString());
      }

      var isCancelled = false;
      onStoring(ref isCancelled);
      if (isCancelled) return;

      DC.Data._SingleChildParentNRs.Add(this);
      onStored();
#if DEBUG
      DC.Trace?.Invoke($"Stored SingleChildParentNR #{GetHashCode()} @{Key}");
#endif
    }
    partial void onStoring(ref bool isCancelled);
    partial void onStored();


    /// <summary>
    /// Estimated number of UTF8 characters needed to write SingleChildParentNR to CSV file
    /// </summary>
    public const int EstimatedLineLength = 150;


    /// <summary>
    /// Write SingleChildParentNR to CSV file
    /// </summary>
    internal static void Write(SingleChildParentNR singleChildParentNR, CsvWriter csvWriter) {
      singleChildParentNR.onCsvWrite();
      csvWriter.Write(singleChildParentNR.Text);
    }
    partial void onCsvWrite();


    /// <summary>
    /// Updates SingleChildParentNR with the provided values
    /// </summary>
    public void Update(string text) {
      var clone = new SingleChildParentNR(this);
      var isCancelled = false;
      onUpdating(text, ref isCancelled);
      if (isCancelled) return;

#if DEBUG
      DC.Trace?.Invoke($"Updating SingleChildParentNR: {ToTraceString()}");
#endif

      //update properties and detect if any value has changed
      var isChangeDetected = false;
      if (Text!=text) {
        Text = text;
        isChangeDetected = true;
      }
      if (isChangeDetected) {
        onUpdated(clone);
        if (Key>=0) {
          DC.Data._SingleChildParentNRs.ItemHasChanged(clone, this);
        } else if (DC.Data.IsTransaction) {
          DC.Data.AddTransaction(new TransactionItem(8, TransactionActivityEnum.Update, Key, this, oldItem: clone));
        }
        HasChanged?.Invoke(clone, this);
      }
#if DEBUG
      DC.Trace?.Invoke($"Updated SingleChildParentNR: {ToTraceString()}");
#endif
    }
    partial void onUpdating(string text, ref bool isCancelled);
    partial void onUpdated(SingleChildParentNR old);


    /// <summary>
    /// Updates this SingleChildParentNR with values from CSV file
    /// </summary>
    internal static void Update(SingleChildParentNR singleChildParentNR, CsvReader csvReader){
      singleChildParentNR.Text = csvReader.ReadString();
      singleChildParentNR.onCsvUpdate();
    }
    partial void onCsvUpdate();


    /// <summary>
    /// Add singleChildChild to Child.
    /// </summary>
    internal void AddToChild(SingleChildChild singleChildChild) {
#if DEBUG
      if (singleChildChild==SingleChildChild.NoSingleChildChild) throw new Exception();
      if ((singleChildChild.Key>=0)&&(Key<0)) throw new Exception();
      if(Child==singleChildChild) throw new Exception();
#endif
      if (Child!=null) {
        throw new Exception($"SingleChildParentNR.AddToChild(): '{Child}' is already assigned to Child, it is not possible to assign now '{singleChildChild}'.");
      }
      Child = singleChildChild;
      onAddedToChild(singleChildChild);
#if DEBUG
      DC.Trace?.Invoke($"Add SingleChildChild {singleChildChild.GetKeyOrHash()} to " +
        $"{this.GetKeyOrHash()} SingleChildParentNR.Child");
#endif
    }
    partial void onAddedToChild(SingleChildChild singleChildChild);


    /// <summary>
    /// Removes singleChildChild from SingleChildParentNR.
    /// </summary>
    internal void RemoveFromChild(SingleChildChild singleChildChild) {
#if DEBUG
      if (Child!=singleChildChild) {
        throw new Exception($"SingleChildParentNR.RemoveFromChild(): Child does not link to singleChildChild '{singleChildChild}' but '{Child}'.");
      }
#endif
      Child = null;
      onRemovedFromChild(singleChildChild);
#if DEBUG
      DC.Trace?.Invoke($"Remove SingleChildChild {singleChildChild.GetKeyOrHash()} from " +
        $"{this.GetKeyOrHash()} SingleChildParentNR.Child");
#endif
    }
    partial void onRemovedFromChild(SingleChildChild singleChildChild);


    /// <summary>
    /// Removes SingleChildParentNR from DC.Data.SingleChildParentNRs.
    /// </summary>
    public void Release() {
      if (Key<0) {
        throw new Exception($"SingleChildParentNR.Release(): SingleChildParentNR '{this}' is not stored in DC.Data, key is {Key}.");
      }
      if (Child?.Key>=0) {
        throw new Exception($"Cannot release SingleChildParentNR '{this}' " + Environment.NewLine + 
          $"because '{Child}' in SingleChildParentNR.Child is still stored.");
      }
      onReleased();
      DC.Data._SingleChildParentNRs.Remove(Key);
#if DEBUG
      DC.Trace?.Invoke($"Released SingleChildParentNR @{Key} #{GetHashCode()}");
#endif
    }
    partial void onReleased();


    /// <summary>
    /// Undoes the new() statement as part of a transaction rollback.
    /// </summary>
    internal static void RollbackItemNew(IStorageItem item) {
      var singleChildParentNR = (SingleChildParentNR) item;
#if DEBUG
      DC.Trace?.Invoke($"Rollback new SingleChildParentNR(): {singleChildParentNR.ToTraceString()}");
#endif
      singleChildParentNR.onRollbackItemNew();
    }
    partial void onRollbackItemNew();


    /// <summary>
    /// Releases SingleChildParentNR from DC.Data.SingleChildParentNRs as part of a transaction rollback of Store().
    /// </summary>
    internal static void RollbackItemStore(IStorageItem item) {
      var singleChildParentNR = (SingleChildParentNR) item;
#if DEBUG
      DC.Trace?.Invoke($"Rollback SingleChildParentNR.Store(): {singleChildParentNR.ToTraceString()}");
#endif
      singleChildParentNR.onRollbackItemStored();
    }
    partial void onRollbackItemStored();


    /// <summary>
    /// Restores the SingleChildParentNR item data as it was before the last update as part of a transaction rollback.
    /// </summary>
    internal static void RollbackItemUpdate(IStorageItem oldStorageItem, IStorageItem newStorageItem) {
      var oldItem = (SingleChildParentNR) oldStorageItem;//an item clone with the values before item was updated
      var item = (SingleChildParentNR) newStorageItem;//is the instance whose values should be restored
#if DEBUG
      DC.Trace?.Invoke($"Rolling back SingleChildParentNR.Update(): {item.ToTraceString()}");
#endif

      // updated item: restore old values
      item.Text = oldItem.Text;
      item.onRollbackItemUpdated(oldItem);
#if DEBUG
      DC.Trace?.Invoke($"Rolled back SingleChildParentNR.Update(): {item.ToTraceString()}");
#endif
    }
    partial void onRollbackItemUpdated(SingleChildParentNR oldSingleChildParentNR);


    /// <summary>
    /// Adds SingleChildParentNR to DC.Data.SingleChildParentNRs as part of a transaction rollback of Release().
    /// </summary>
    internal static void RollbackItemRelease(IStorageItem item) {
      var singleChildParentNR = (SingleChildParentNR) item;
#if DEBUG
      DC.Trace?.Invoke($"Rollback SingleChildParentNR.Release(): {singleChildParentNR.ToTraceString()}");
#endif
      singleChildParentNR.onRollbackItemRelease();
    }
    partial void onRollbackItemRelease();


    /// <summary>
    /// Returns property values for tracing. Parents are shown with their key instead their content.
    /// </summary>
    public string ToTraceString() {
      var returnString =
        $"{this.GetKeyOrHash()}|" +
        $" {Text}";
      onToTraceString(ref returnString);
      return returnString;
    }
    partial void onToTraceString(ref string returnString);


    /// <summary>
    /// Returns property values
    /// </summary>
    public string ToShortString() {
      var returnString =
        $"{Key.ToKeyString()}," +
        $" {Text}";
      onToShortString(ref returnString);
      return returnString;
    }
    partial void onToShortString(ref string returnString);


    /// <summary>
    /// Returns all property names and values
    /// </summary>
    public override string ToString() {
      var returnString =
        $"Key: {Key.ToKeyString()}," +
        $" Text: {Text}," +
        $" Child: {Child?.ToShortString()};";
      onToString(ref returnString);
      return returnString;
    }
    partial void onToString(ref string returnString);
    #endregion
  }
}
